//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.09 at 02:35:55 PM BST 
//


package org.atlasapi.remotesite.pa.bindings;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "attr")
public class Attr {

    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String stereo;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String subtitles;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String repeat;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String bw;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String premiere;
    @XmlAttribute(name = "new_series")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String newSeries;
    @XmlAttribute(name = "last_in_series")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String lastInSeries;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String surround;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String widescreen;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String film;
    @XmlAttribute(name = "sign_lang")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String signLang;
    @XmlAttribute(name = "in_vision")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String inVision;
    @XmlAttribute(name = "audio_des")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String audioDes;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String interactive;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String hd;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String live;
    @XmlAttribute(name = "as_live")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String asLive;
    @XmlAttribute(name = "follow_on")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String followOn;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String choice;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String familychoice;
    @XmlAttribute(name = "tv_movie")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String tvMovie;
    @XmlAttribute(name = "web_choice")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String webChoice;

    /**
     * Gets the value of the stereo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStereo() {
        if (stereo == null) {
            return "no";
        } else {
            return stereo;
        }
    }

    /**
     * Sets the value of the stereo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStereo(String value) {
        this.stereo = value;
    }

    /**
     * Gets the value of the subtitles property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubtitles() {
        if (subtitles == null) {
            return "no";
        } else {
            return subtitles;
        }
    }

    /**
     * Sets the value of the subtitles property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubtitles(String value) {
        this.subtitles = value;
    }

    /**
     * Gets the value of the repeat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRepeat() {
        if (repeat == null) {
            return "no";
        } else {
            return repeat;
        }
    }

    /**
     * Sets the value of the repeat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRepeat(String value) {
        this.repeat = value;
    }

    /**
     * Gets the value of the bw property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBw() {
        if (bw == null) {
            return "no";
        } else {
            return bw;
        }
    }

    /**
     * Sets the value of the bw property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBw(String value) {
        this.bw = value;
    }

    /**
     * Gets the value of the premiere property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPremiere() {
        if (premiere == null) {
            return "no";
        } else {
            return premiere;
        }
    }

    /**
     * Sets the value of the premiere property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPremiere(String value) {
        this.premiere = value;
    }

    /**
     * Gets the value of the newSeries property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewSeries() {
        if (newSeries == null) {
            return "no";
        } else {
            return newSeries;
        }
    }

    /**
     * Sets the value of the newSeries property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewSeries(String value) {
        this.newSeries = value;
    }

    /**
     * Gets the value of the lastInSeries property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastInSeries() {
        if (lastInSeries == null) {
            return "no";
        } else {
            return lastInSeries;
        }
    }

    /**
     * Sets the value of the lastInSeries property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastInSeries(String value) {
        this.lastInSeries = value;
    }

    /**
     * Gets the value of the surround property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSurround() {
        if (surround == null) {
            return "no";
        } else {
            return surround;
        }
    }

    /**
     * Sets the value of the surround property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSurround(String value) {
        this.surround = value;
    }

    /**
     * Gets the value of the widescreen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWidescreen() {
        if (widescreen == null) {
            return "no";
        } else {
            return widescreen;
        }
    }

    /**
     * Sets the value of the widescreen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWidescreen(String value) {
        this.widescreen = value;
    }

    /**
     * Gets the value of the film property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFilm() {
        if (film == null) {
            return "no";
        } else {
            return film;
        }
    }

    /**
     * Sets the value of the film property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFilm(String value) {
        this.film = value;
    }

    /**
     * Gets the value of the signLang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSignLang() {
        if (signLang == null) {
            return "no";
        } else {
            return signLang;
        }
    }

    /**
     * Sets the value of the signLang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSignLang(String value) {
        this.signLang = value;
    }

    /**
     * Gets the value of the inVision property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInVision() {
        if (inVision == null) {
            return "no";
        } else {
            return inVision;
        }
    }

    /**
     * Sets the value of the inVision property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInVision(String value) {
        this.inVision = value;
    }

    /**
     * Gets the value of the audioDes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAudioDes() {
        if (audioDes == null) {
            return "no";
        } else {
            return audioDes;
        }
    }

    /**
     * Sets the value of the audioDes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAudioDes(String value) {
        this.audioDes = value;
    }

    /**
     * Gets the value of the interactive property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInteractive() {
        if (interactive == null) {
            return "no";
        } else {
            return interactive;
        }
    }

    /**
     * Sets the value of the interactive property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInteractive(String value) {
        this.interactive = value;
    }

    /**
     * Gets the value of the hd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHd() {
        if (hd == null) {
            return "no";
        } else {
            return hd;
        }
    }

    /**
     * Sets the value of the hd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHd(String value) {
        this.hd = value;
    }

    /**
     * Gets the value of the live property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLive() {
        if (live == null) {
            return "no";
        } else {
            return live;
        }
    }

    /**
     * Sets the value of the live property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLive(String value) {
        this.live = value;
    }

    /**
     * Gets the value of the asLive property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAsLive() {
        if (asLive == null) {
            return "no";
        } else {
            return asLive;
        }
    }

    /**
     * Sets the value of the asLive property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAsLive(String value) {
        this.asLive = value;
    }

    /**
     * Gets the value of the followOn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFollowOn() {
        if (followOn == null) {
            return "no";
        } else {
            return followOn;
        }
    }

    /**
     * Sets the value of the followOn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFollowOn(String value) {
        this.followOn = value;
    }

    /**
     * Gets the value of the choice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChoice() {
        if (choice == null) {
            return "no";
        } else {
            return choice;
        }
    }

    /**
     * Sets the value of the choice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChoice(String value) {
        this.choice = value;
    }

    /**
     * Gets the value of the familychoice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFamilychoice() {
        if (familychoice == null) {
            return "no";
        } else {
            return familychoice;
        }
    }

    /**
     * Sets the value of the familychoice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFamilychoice(String value) {
        this.familychoice = value;
    }

    /**
     * Gets the value of the tvMovie property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTvMovie() {
        if (tvMovie == null) {
            return "no";
        } else {
            return tvMovie;
        }
    }

    /**
     * Sets the value of the tvMovie property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTvMovie(String value) {
        this.tvMovie = value;
    }

    /**
     * Gets the value of the webChoice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWebChoice() {
        if (webChoice == null) {
            return "no";
        } else {
            return webChoice;
        }
    }

    /**
     * Sets the value of the webChoice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWebChoice(String value) {
        this.webChoice = value;
    }

}
