//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.22 at 12:06:36 PM BST 
//


package org.atlasapi.remotesite.pa.bindings;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "epgdetails",
    "progData"
})
@XmlRootElement(name = "channel_data")
public class ChannelData {

    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String name;
    @XmlAttribute(name = "channel_id", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String channelId;
    protected Epgdetails epgdetails;
    @XmlElement(name = "prog_data", required = true)
    protected List<ProgData> progData;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the channelId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChannelId() {
        return channelId;
    }

    /**
     * Sets the value of the channelId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChannelId(String value) {
        this.channelId = value;
    }

    /**
     * Gets the value of the epgdetails property.
     * 
     * @return
     *     possible object is
     *     {@link Epgdetails }
     *     
     */
    public Epgdetails getEpgdetails() {
        return epgdetails;
    }

    /**
     * Sets the value of the epgdetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link Epgdetails }
     *     
     */
    public void setEpgdetails(Epgdetails value) {
        this.epgdetails = value;
    }

    /**
     * Gets the value of the progData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the progData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProgData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProgData }
     * 
     * 
     */
    public List<ProgData> getProgData() {
        if (progData == null) {
            progData = new ArrayList<ProgData>();
        }
        return this.progData;
    }

}
