//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.01 at 02:20:03 PM GMT 
//


package org.atlasapi.remotesite.pa.bindings;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.atlasapi.remotesite.pa.bindings package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.atlasapi.remotesite.pa.bindings
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Picture }
     * 
     */
    public Picture createPicture() {
        return new Picture();
    }

    /**
     * Create an instance of {@link RtCategory }
     * 
     */
    public RtCategory createRtCategory() {
        return new RtCategory();
    }

    /**
     * Create an instance of {@link ProgData }
     * 
     */
    public ProgData createProgData() {
        return new ProgData();
    }

    /**
     * Create an instance of {@link Warning }
     * 
     */
    public Warning createWarning() {
        return new Warning();
    }

    /**
     * Create an instance of {@link ChannelData }
     * 
     */
    public ChannelData createChannelData() {
        return new ChannelData();
    }

    /**
     * Create an instance of {@link Attr }
     * 
     */
    public Attr createAttr() {
        return new Attr();
    }

    /**
     * Create an instance of {@link TvData }
     * 
     */
    public TvData createTvData() {
        return new TvData();
    }

    /**
     * Create an instance of {@link Billings }
     * 
     */
    public Billings createBillings() {
        return new Billings();
    }

    /**
     * Create an instance of {@link Category }
     * 
     */
    public Category createCategory() {
        return new Category();
    }

    /**
     * Create an instance of {@link StaffMember }
     * 
     */
    public StaffMember createStaffMember() {
        return new StaffMember();
    }

    /**
     * Create an instance of {@link CastMember }
     * 
     */
    public CastMember createCastMember() {
        return new CastMember();
    }

    /**
     * Create an instance of {@link ListingsDate }
     * 
     */
    public ListingsDate createListingsDate() {
        return new ListingsDate();
    }

    /**
     * Create an instance of {@link Epg }
     * 
     */
    public Epg createEpg() {
        return new Epg();
    }

    /**
     * Create an instance of {@link Billing }
     * 
     */
    public Billing createBilling() {
        return new Billing();
    }

    /**
     * Create an instance of {@link Epgdetails }
     * 
     */
    public Epgdetails createEpgdetails() {
        return new Epgdetails();
    }

}
