//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.01 at 02:20:03 PM GMT 
//


package org.atlasapi.remotesite.pa.bindings;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "maincat",
    "subcat"
})
@XmlRootElement(name = "rt_category")
public class RtCategory {

    @XmlElement(required = true)
    protected String maincat;
    protected String subcat;

    /**
     * Gets the value of the maincat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaincat() {
        return maincat;
    }

    /**
     * Sets the value of the maincat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaincat(String value) {
        this.maincat = value;
    }

    /**
     * Gets the value of the subcat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubcat() {
        return subcat;
    }

    /**
     * Sets the value of the subcat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubcat(String value) {
        this.subcat = value;
    }

}
