package org.atlasapi.remotesite.pa;

import org.atlasapi.genres.AtlasGenre;
import org.atlasapi.genres.GenreMap;

public class PaGenreMap extends GenreMap {
    static {
		// movie/drama
		genres.put("http://pressassociation.com/genres/1000", AtlasGenre.DRAMA);
		genres.put("http://pressassociation.com/genres/1F00", AtlasGenre.DRAMA);
		genres.put("http://pressassociation.com/genres/1F01", AtlasGenre.DRAMA);
		genres.put("http://pressassociation.com/genres/1F05", AtlasGenre.DRAMA);
		genres.put("http://pressassociation.com/genres/1F06", AtlasGenre.CHILDRENS);
		genres.put("http://pressassociation.com/genres/1F07", AtlasGenre.DRAMA);
		genres.put("http://pressassociation.com/genres/1F08", AtlasGenre.DRAMA);
		genres.put("http://pressassociation.com/genres/1F09", AtlasGenre.DRAMA);
		genres.put("http://pressassociation.com/genres/1100", AtlasGenre.DRAMA);
		genres.put("http://pressassociation.com/genres/1F0A", AtlasGenre.DRAMA);
		genres.put("http://pressassociation.com/genres/1F0B", AtlasGenre.DRAMA);
		genres.put("http://pressassociation.com/genres/1F0C", AtlasGenre.DRAMA);
		genres.put("http://pressassociation.com/genres/1F0D", AtlasGenre.DRAMA);
		genres.put("http://pressassociation.com/genres/1F0E", AtlasGenre.DRAMA);
		genres.put("http://pressassociation.com/genres/1F04", AtlasGenre.DRAMA);
		genres.put("http://pressassociation.com/genres/1200", AtlasGenre.DRAMA);
		genres.put("http://pressassociation.com/genres/1F0F", AtlasGenre.DRAMA);
		genres.put("http://pressassociation.com/genres/1F10", AtlasGenre.DRAMA);
		genres.put("http://pressassociation.com/genres/1F11", AtlasGenre.DRAMA);
		genres.put("http://pressassociation.com/genres/1300", AtlasGenre.DRAMA);
		genres.put("http://pressassociation.com/genres/1F02", AtlasGenre.DRAMA);
		genres.put("http://pressassociation.com/genres/1F03", AtlasGenre.DRAMA);
		genres.put("http://pressassociation.com/genres/1400", AtlasGenre.COMEDY);
		genres.put("http://pressassociation.com/genres/1F12", AtlasGenre.COMEDY);
		genres.put("http://pressassociation.com/genres/1F13", AtlasGenre.COMEDY);
		genres.put("http://pressassociation.com/genres/1F14", AtlasGenre.COMEDY);
		genres.put("http://pressassociation.com/genres/1500", AtlasGenre.ENTERTAINMENT);
		genres.put("http://pressassociation.com/genres/1600", AtlasGenre.DRAMA);
		genres.put("http://pressassociation.com/genres/1F15", AtlasGenre.DRAMA);
		genres.put("http://pressassociation.com/genres/1700", AtlasGenre.DRAMA);
		genres.put("http://pressassociation.com/genres/1F17", AtlasGenre.DRAMA);
		genres.put("http://pressassociation.com/genres/1F16", AtlasGenre.DRAMA);
		genres.put("http://pressassociation.com/genres/1800", AtlasGenre.DRAMA);

		// news/current affairs
		genres.put("http://pressassociation.com/genres/2000", AtlasGenre.NEWS);
		genres.put("http://pressassociation.com/genres/2F02", AtlasGenre.NEWS);
		genres.put("http://pressassociation.com/genres/2F03", AtlasGenre.NEWS);
		genres.put("http://pressassociation.com/genres/2F04", AtlasGenre.NEWS);
		genres.put("http://pressassociation.com/genres/2F05", AtlasGenre.NEWS);
		genres.put("http://pressassociation.com/genres/2F06", AtlasGenre.NEWS);
		genres.put("http://pressassociation.com/genres/2200", AtlasGenre.NEWS);
		genres.put("http://pressassociation.com/genres/2300", AtlasGenre.NEWS);
		genres.put("http://pressassociation.com/genres/2F07", AtlasGenre.NEWS);
		genres.put("http://pressassociation.com/genres/2F08", AtlasGenre.NEWS);

		// show/game show
		genres.put("http://pressassociation.com/genres/3000", AtlasGenre.ENTERTAINMENT);
		genres.put("http://pressassociation.com/genres/3F00", AtlasGenre.ENTERTAINMENT);
		genres.put("http://pressassociation.com/genres/3F01", AtlasGenre.ENTERTAINMENT);
		genres.put("http://pressassociation.com/genres/3F02", AtlasGenre.ENTERTAINMENT);
		genres.put("http://pressassociation.com/genres/3100", AtlasGenre.ENTERTAINMENT);
		genres.put("http://pressassociation.com/genres/3F03", AtlasGenre.ENTERTAINMENT);
		genres.put("http://pressassociation.com/genres/3200", AtlasGenre.ENTERTAINMENT);
		genres.put("http://pressassociation.com/genres/3300", AtlasGenre.ENTERTAINMENT);

		// sports
		genres.put("http://pressassociation.com/genres/4000", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4100", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4200", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4300", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4400", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4500", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4600", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4700", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4800", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4900", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4A00", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4B00", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F00", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F01", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F02", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F03", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F04", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F05", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F06", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F07", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F08", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F09", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F0A", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F0B", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F0C", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F0D", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F0E", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F0F", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F10", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F11", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F12", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F13", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F14", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F15", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F16", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F17", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F19", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F1A", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F1B", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F1C", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F1D", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F1E", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F1F", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F20", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F21", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F22", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F23", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F24", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F25", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F26", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F27", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F28", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F29", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F2A", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F2B", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F2C", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F2D", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F2E", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F2F", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F30", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F31", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F32", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F33", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F34", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F35", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F36", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F37", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F39", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F3A", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F3B", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F3C", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F3D", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F3E", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F3F", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F40", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F41", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F42", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F43", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F44", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F45", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F46", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F47", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F48", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F49", AtlasGenre.SPORT);
		genres.put("http://pressassociation.com/genres/4F4A", AtlasGenre.SPORT);

		// children's/youth
		genres.put("http://pressassociation.com/genres/5000", AtlasGenre.CHILDRENS);
		genres.put("http://pressassociation.com/genres/5100", AtlasGenre.CHILDRENS);
		genres.put("http://pressassociation.com/genres/5200", AtlasGenre.CHILDRENS);
		genres.put("http://pressassociation.com/genres/5300", AtlasGenre.CHILDRENS);
		genres.put("http://pressassociation.com/genres/5400", AtlasGenre.CHILDRENS);
		genres.put("http://pressassociation.com/genres/5500", AtlasGenre.CHILDRENS);

		// music/ballet/dance
		genres.put("http://pressassociation.com/genres/6000", AtlasGenre.MUSIC);
		genres.put("http://pressassociation.com/genres/6F01", AtlasGenre.MUSIC);
		genres.put("http://pressassociation.com/genres/6F02", AtlasGenre.MUSIC);
		genres.put("http://pressassociation.com/genres/6F03", AtlasGenre.MUSIC);
		genres.put("http://pressassociation.com/genres/6F06", AtlasGenre.MUSIC);
		genres.put("http://pressassociation.com/genres/6F07", AtlasGenre.MUSIC);
		genres.put("http://pressassociation.com/genres/6F08", AtlasGenre.MUSIC);
		genres.put("http://pressassociation.com/genres/6200", AtlasGenre.MUSIC);
		genres.put("http://pressassociation.com/genres/6300", AtlasGenre.MUSIC);
		genres.put("http://pressassociation.com/genres/6400", AtlasGenre.MUSIC);
		genres.put("http://pressassociation.com/genres/6F09", AtlasGenre.MUSIC);
		genres.put("http://pressassociation.com/genres/6F0A", AtlasGenre.MUSIC);
		genres.put("http://pressassociation.com/genres/6600", AtlasGenre.MUSIC);
		genres.put("http://pressassociation.com/genres/6F05", AtlasGenre.MUSIC);

		// arts/culture (without music)
		genres.put("http://pressassociation.com/genres/7000", AtlasGenre.FACTUAL);
		genres.put("http://pressassociation.com/genres/7100", AtlasGenre.FACTUAL);
		genres.put("http://pressassociation.com/genres/7200", AtlasGenre.FACTUAL);
		genres.put("http://pressassociation.com/genres/7400", AtlasGenre.FACTUAL);
		genres.put("http://pressassociation.com/genres/7500", AtlasGenre.FACTUAL);
		genres.put("http://pressassociation.com/genres/7600", AtlasGenre.FACTUAL);
		genres.put("http://pressassociation.com/genres/7700", AtlasGenre.FACTUAL);
		genres.put("http://pressassociation.com/genres/7800", AtlasGenre.FACTUAL);
		genres.put("http://pressassociation.com/genres/7900", AtlasGenre.FACTUAL);
		genres.put("http://pressassociation.com/genres/7A00", AtlasGenre.FACTUAL);
		genres.put("http://pressassociation.com/genres/7B00", AtlasGenre.FACTUAL);

		// social/political/economics
		genres.put("http://pressassociation.com/genres/8000", AtlasGenre.FACTUAL);
		genres.put("http://pressassociation.com/genres/8200", AtlasGenre.FACTUAL);

		// education/science/factual
		genres.put("http://pressassociation.com/genres/9000", AtlasGenre.LIFESTYLE);
		genres.put("http://pressassociation.com/genres/9F01", AtlasGenre.LIFESTYLE);
		genres.put("http://pressassociation.com/genres/9F02", AtlasGenre.LIFESTYLE);
		genres.put("http://pressassociation.com/genres/9F03", AtlasGenre.FACTUAL);
		genres.put("http://pressassociation.com/genres/9F04", AtlasGenre.FACTUAL);
		genres.put("http://pressassociation.com/genres/9F05", AtlasGenre.FACTUAL);
		genres.put("http://pressassociation.com/genres/9F06", AtlasGenre.FACTUAL);
		genres.put("http://pressassociation.com/genres/9100", AtlasGenre.FACTUAL);
		genres.put("http://pressassociation.com/genres/9F07", AtlasGenre.FACTUAL);
		genres.put("http://pressassociation.com/genres/9F08", AtlasGenre.FACTUAL);
		genres.put("http://pressassociation.com/genres/9F09", AtlasGenre.FACTUAL);
		genres.put("http://pressassociation.com/genres/9F0A", AtlasGenre.FACTUAL);
		genres.put("http://pressassociation.com/genres/9200", AtlasGenre.FACTUAL);
		genres.put("http://pressassociation.com/genres/9300", AtlasGenre.FACTUAL);
		genres.put("http://pressassociation.com/genres/9400", AtlasGenre.FACTUAL);
		genres.put("http://pressassociation.com/genres/9500", AtlasGenre.FACTUAL);
		genres.put("http://pressassociation.com/genres/9F00", AtlasGenre.LEARNING);
		genres.put("http://pressassociation.com/genres/9700", AtlasGenre.LEARNING);

		// leisure/hobbies
		genres.put("http://pressassociation.com/genres/A000", AtlasGenre.LIFESTYLE);
		genres.put("http://pressassociation.com/genres/AF01", AtlasGenre.LIFESTYLE);
		genres.put("http://pressassociation.com/genres/AF02", AtlasGenre.LIFESTYLE);
		genres.put("http://pressassociation.com/genres/A100", AtlasGenre.LIFESTYLE);
		genres.put("http://pressassociation.com/genres/A200", AtlasGenre.LIFESTYLE);
		genres.put("http://pressassociation.com/genres/A300", AtlasGenre.LIFESTYLE);
		genres.put("http://pressassociation.com/genres/A400", AtlasGenre.LIFESTYLE);
		genres.put("http://pressassociation.com/genres/A500", AtlasGenre.LIFESTYLE);
		genres.put("http://pressassociation.com/genres/A600", AtlasGenre.LIFESTYLE);
		genres.put("http://pressassociation.com/genres/A700", AtlasGenre.LIFESTYLE);
		genres.put("http://pressassociation.com/genres/AF00", AtlasGenre.LIFESTYLE);
		genres.put("http://pressassociation.com/genres/AF03", AtlasGenre.LIFESTYLE);

		// special
		//genres.put("http://pressassociation.com/genres/B300", AtlasGenre.);
		//genres.put("http://pressassociation.com/genres/BF00", AtlasGenre.);
		genres.put("http://pressassociation.com/genres/BF01", AtlasGenre.FILM);
    }
}
