package org.atlasapi;

import java.util.List;

import org.atlasapi.media.channel.MongoChannelGroupStore;
import org.atlasapi.media.channel.MongoChannelStore;
import org.atlasapi.media.channel.OldChannel;
import org.atlasapi.media.entity.MediaType;
import org.atlasapi.media.entity.Publisher;

import com.google.common.collect.ImmutableBiMap;
import com.google.common.collect.ImmutableList;
import com.google.common.collect.ImmutableMap;
import com.google.common.collect.ImmutableMultimap;
import com.metabroadcast.common.persistence.mongo.DatabasedMongo;
import com.mongodb.Mongo;

public class MongoChannelInitialPopulate {

	public static void main(String[] args) throws Exception {
		Mongo mongo = new Mongo(System.getProperty("mongo.host", "127.0.0.1"));
		String dbName = System.getProperty("mongo.dbName", "atlas");
        DatabasedMongo dbMongo = new DatabasedMongo(mongo, dbName);
        System.out.println(String.format("Writing channels to %s", dbName));
		System.out.println(String.format("Wrote %s channels", writeChannels(dbMongo)));
	}

    public static int writeChannels(DatabasedMongo dbMongo) {
        MongoChannelGroupStore channelGroupStore = new MongoChannelGroupStore(dbMongo);
        MongoChannelStore store = new MongoChannelStore(dbMongo, channelGroupStore, channelGroupStore);
		int written = 0;
		for(OldChannel oldChannel: OldChannel.all()) {
			if(oldChannel.getTitle().toLowerCase().contains("radio") || NEW_RADIO_STATIONS.contains(oldChannel)) {
				oldChannel.setMediaType(MediaType.AUDIO);
			}
			else {
				oldChannel.setMediaType(MediaType.VIDEO);
			}
			if(XMLTV_MAP.containsKey(oldChannel)) {
				for(Integer id : XMLTV_MAP.get(oldChannel)) {
					oldChannel.addAliasUrl(String.format("http://xmltv.radiotimes.com/channels/%d", id));
					// TODO new alias
				}
			}
			if(PA_CHANNEL_MAP.containsKey(oldChannel)) {
				Integer id = PA_CHANNEL_MAP.get(oldChannel);
				oldChannel.addAliasUrl(String.format("http://pressassociation.com/channels/%d", id));
				// TODO new alias
			}
			if(REDUX_CHANNEL_MAP.containsKey(oldChannel)) {
				String id = REDUX_CHANNEL_MAP.get(oldChannel);
				oldChannel.addAliasUrl(String.format("http://devapi.bbcredux.com/channels/%s", id));
				// TODO new alias
			}
			oldChannel.setSource(Publisher.METABROADCAST);
			oldChannel.setCanonicalUri(oldChannel.getUri());
			oldChannel.addTitle(oldChannel.getTitle());
			store.createOrUpdate(oldChannel);
			written++;
		}
        return written;
    }

	private static final ImmutableMap<OldChannel, Integer> PA_CHANNEL_MAP = ImmutableBiMap.<OldChannel, Integer> builder()
			.put( OldChannel.BBC_ONE, 4)
			.put( OldChannel.BBC_ONE_NORTHERN_IRELAND, 1)
			.put( OldChannel.BBC_ONE_SCOTLAND, 2)
			.put( OldChannel.BBC_ONE_WALES, 3)
			.put( OldChannel.BBC_ONE_EAST, 9)
			.put( OldChannel.BBC_ONE_EAST_MIDLANDS, 10)
			.put( OldChannel.BBC_ONE_WEST_MIDLANDS, 11)
			.put( OldChannel.BBC_ONE_YORKSHIRE, 12)
			.put( OldChannel.BBC_ONE_NORTH_EAST, 13)
			.put( OldChannel.BBC_ONE_NORTH_WEST, 14)
			.put( OldChannel.BBC_ONE_SOUTH, 15)
			.put( OldChannel.BBC_ONE_SOUTH_EAST, 16)
			.put( OldChannel.BBC_ONE_SOUTH_WEST, 17)
			.put( OldChannel.BBC_ONE_WEST, 18)
			.put( OldChannel.BBC_ONE_HD, 1609)
			.put( OldChannel.BBC_TWO, 52)
			.put( OldChannel.BBC_TWO_NORTHERN_IRELAND, 19)
			.put( OldChannel.BBC_TWO_SCOTLAND, 20)
			.put( OldChannel.BBC_TWO_WALES, 21)
			.put( OldChannel.BBC_THREE, 935)
			.put( OldChannel.BBC_FOUR, 742)
			.put( OldChannel.BBC_HD, 1228)
			.put( OldChannel.CBEEBIES, 734)
			.put( OldChannel.CBBC, 733)
			.put( OldChannel.BBC_NEWS, 85)
			.put( OldChannel.BBC_PARLIMENT, 56)
			.put( OldChannel.BBC_WORLD_NEWS, 138)
			.put( OldChannel.ITV1_LONDON, 49)
			.put( OldChannel.ITV1_GRANADA, 35)
			.put( OldChannel.ITV1_TYNE_TEES, 37)
			.put( OldChannel.ITV1_BORDER_SOUTH, 38)
			.put( OldChannel.ITV1_MERIDIAN, 42)
			.put( OldChannel.ITV1_ANGLIA, 43)
			.put( OldChannel.ITV1_CHANNEL, 44)
			.put( OldChannel.ITV1_WALES, 45)
			.put( OldChannel.ITV1_WEST, 46)
			.put( OldChannel.ITV1_CARLTON_CENTRAL, 47)
			.put( OldChannel.ITV1_CARLTON_WESTCOUNTRY, 48)
			.put( OldChannel.ITV1_BORDER_NORTH, 698)
			.put( OldChannel.ITV1_THAMES_VALLEY_NORTH, 1296)
			.put( OldChannel.ITV1_THAMES_VALLEY_SOUTH, 1297)
			.put( OldChannel.ITV1_HD, 1560)
			//.put( OldChannel.ITV1_CARLTON_CENTRAL, 47)
			.put( OldChannel.ITV2, 451)
			.put( OldChannel.ITV2_HD, 1602)
			.put( OldChannel.ITV3, 1065)
			.put( OldChannel.ITV3_HD, 1612)
			.put( OldChannel.ITV4, 1174)
			.put( OldChannel.ITV4_HD, 1613)
			.put( OldChannel.CHANNEL_FOUR, 53)
			.put( OldChannel.E_FOUR, 605)
			.put( OldChannel.MORE_FOUR, 1167)
			.put( OldChannel.FILM_4, 220)
			.put( OldChannel.FOUR_MUSIC, 1438)
			.put( OldChannel.FIVE, 54)
			.put( OldChannel.FIVE_PLUS1, 1661)
			.put( OldChannel.FIVE_HD, 1580)
			.put( OldChannel.FIVER, 1289)
			.put( OldChannel.FIVE_USA, 1290)
			.put( OldChannel.YTV, 36)
			.put( OldChannel.ULSTER, 39)
			.put( OldChannel.ULSTER_HD, 1605)
			.put( OldChannel.STV_CENTRAL, 40)
			.put( OldChannel.STV_HD, 1572)
			.put( OldChannel.STV_NORTH, 41)
			.put( OldChannel.Channel_4_PLUS1, 1379)
			.put( OldChannel.Channel_4_HD, 1404)
			.put( OldChannel.S4C, 645)
			.put( OldChannel.S4C_CLIRLUN, 1563)
			.put( OldChannel.RTE1, 81)
			.put( OldChannel.RTE2, 82)
			.put( OldChannel.TG4, 83)
			.put( OldChannel.TV3, 84)
			.put( OldChannel.GMTV_DIGITAL, 331)
			.put( OldChannel.ITV2_PLUS1, 1291)
			.put( OldChannel.E4_PLUS1, 1055)
			.put( OldChannel.E4_HD, 1534)
			.put( OldChannel.ITV3_PLUS1, 1292)
			.put( OldChannel.MORE4_PLUS1, 1168)
			.put( OldChannel.ITV4_PLUS1, 1457)
			.put( OldChannel.CITV, 1204)
			.put( OldChannel.FIVER_PLUS1, 1485)
			.put( OldChannel.FIVE_USA_PLUS1, 1484)
			.put( OldChannel.MTV_HITS, 59)
			.put( OldChannel.MTV_BASE, 63)
			.put( OldChannel.MTV, 64)
			.put( OldChannel.MTV_PLUS1, 1408)
			.put( OldChannel.TRAVELCHANNEL, 66)
			.put( OldChannel.TRAVELCHANNEL_PLUS1, 943)
			.put( OldChannel.TV5, 67)
			.put( OldChannel.ZEE_TV, 71)
			.put( OldChannel.PHOENIX_CNE, 73)
			.put( OldChannel.CHALLENGE, 170)
			.put( OldChannel.CHALLENGE_PLUS1, 1071)
			.put( OldChannel.HOME, 89)
			.put( OldChannel.HOME_PLUS1, 756)
			.put( OldChannel.SKY_BOX_OFFICE_DIGITAL, 90)
			.put( OldChannel.BLOOMBERG_TV, 92)
			.put( OldChannel.THE_BOX, 93)
			.put( OldChannel.CNN, 95)
			.put( OldChannel.CARTOON_NETWORK, 102)
			.put( OldChannel.GOD_CHANNEL, 99)
			.put( OldChannel.ANIMAL_PLANET, 168)
			.put( OldChannel.ANIMAL_PLANET_PLUS1, 700)
			.put( OldChannel.SKY_NEWS, 114)
			.put( OldChannel.SKY_NEWS_HD, 1564)
			.put( OldChannel.MTV_ROCKS, 120)
			// dupe .put( OldChannel.LIVING, 122)
			.put( OldChannel.LIVING_PLUS1, 987)
			.put( OldChannel.LIVING_HD, 1495)
			.put( OldChannel.BRAVO, 166)
			.put( OldChannel.BRAVO_PLUS1, 986)
			.put( OldChannel.DISCOVERY_HISTORY, 1606)
			.put( OldChannel.DISCOVERY_HISTORY_PLUS_1, 1617)
			.put( OldChannel.DISCOVERY_SCIENCE, 129)
			.put( OldChannel.DISCOVERY_SCIENCE_PLUS1, 1543)
			.put( OldChannel.DISCOVERY_TRAVEL_AND_LIVING, 130)
			.put( OldChannel.DISCOVERY_TRAVEL_AND_LIVING_PLUS1, 1471)
			.put( OldChannel.HISTORY, 171)
			.put( OldChannel.HISTORY_PLUS1, 702)
			.put( OldChannel.NATIONAL_GEOGRAPHIC, 177)
			.put( OldChannel.NATIONAL_GEOGRAPHIC_PLUS1, 710)
			.put( OldChannel.GOLD, 134)
			.put( OldChannel.GOLD_PLUS1, 899)
			.put( OldChannel.THE_DISNEY_CHANNEL, 136)
			.put( OldChannel.THE_DISNEY_CHANNEL_PLUS1, 707)
			// dupe .put( OldChannel.BBC_WORLD_NEWS, 138)
			.put( OldChannel.VH1, 150)
			.put( OldChannel.MTV_CLASSIC, 151)
			.put( OldChannel.DISCOVERY, 169)
			.put( OldChannel.DISCOVERY_PLUS1, 706)
			.put( OldChannel.DISCOVERY_PLUS1_POINT5, 1561)
			.put( OldChannel.DISCOVERY_TURBO, 153)
			.put( OldChannel.ALIBI, 154)
			.put( OldChannel.ALIBI_PLUS1, 1218)
			.put( OldChannel.UNIVERSAL, 155)
			.put( OldChannel.UNIVERSAL_HD, 1569)
			.put( OldChannel.UNIVERSAL_PLUS1, 1527)
			.put( OldChannel.SYFY, 161)
			.put( OldChannel.SYFY_PLUS1, 1213)
			.put( OldChannel.SYFY_HD, 1469)
			.put( OldChannel.COMEDY_CENTRAL, 185)
			.put( OldChannel.COMEDY_CENTRAL_PLUS1, 1165)
			.put( OldChannel.SONY_ENTERTAINMENT_TV_ASIA, 186)
			.put( OldChannel.TCM, 187)
			.put( OldChannel.NICKELODEON, 188)
			.put( OldChannel.NICKELODEON_REPLAY, 703)
			.put( OldChannel.CNBC, 192)
			.put( OldChannel.NICK_JR, 195)
			.put( OldChannel.BOOMERANG, 215)
			.put( OldChannel.BOOMERANG_PLUS1, 1205)
			.put( OldChannel.QVC, 216)
			.put( OldChannel.GBC, 217)
			.put( OldChannel.BBC_ENTERTAINMENT, 218)
			.put( OldChannel.FILM4_HD, 1581)
			.put( OldChannel.FILM4_PLUS1, 708)
			.put( OldChannel.SKY1, 222)
			.put( OldChannel.DISCOVERY_HOME_AND_HEALTH, 227)
			.put( OldChannel.DISCOVERY_HOME_AND_HEALTH_PLUS1, 1148)
			.put( OldChannel.MUTV, 229)
			.put( OldChannel.SKY_SPORTS_NEWS, 231)
			.put( OldChannel.EUROSPORT, 275)
			.put( OldChannel.EUROSPORT_HD, 1434)
			.put( OldChannel.KISS, 410)
			.put( OldChannel.PLAYHOUSE_DISNEY, 418)
			.put( OldChannel.PLAYHOUSE_DISNEY_PLUS, 1399)
			.put( OldChannel.SKY_SPORTS_1, 431)
			.put( OldChannel.SKY_SPORTS_2, 433)
			.put( OldChannel.SKY_SPORTS_3, 435)
			.put( OldChannel.SKY_SPORTS_4, 437)
			.put( OldChannel.BIO, 474)
			.put( OldChannel.BID_TV, 485)
			.put( OldChannel.SKY_ARTS_1, 602)
			.put( OldChannel.EURONEWS, 614)
			.put( OldChannel.B4U_MOVIES, 619)
			.put( OldChannel.EXTREME_SPORTS, 663)
			.put( OldChannel.MTV_DANCE, 664)
			.put( OldChannel.STAR_PLUS, 678)
			.put( OldChannel.TELEG, 691)
			.put( OldChannel.CHANNEL_9, 696)
			.put( OldChannel.GOOD_FOOD, 722)
			.put( OldChannel.GOOD_FOOD_PLUS1, 988)
			.put( OldChannel.ATTHERACES, 747)
			.put( OldChannel.NICKTOONS_TV, 874)
			.put( OldChannel.NICKTOONS_REPLAY, 1546)
			.put( OldChannel.CHART_SHOW_TV, 906)
			.put( OldChannel.YESTERDAY, 908)
			.put( OldChannel.YESTERDAY_PLUS1, 1068)
			.put( OldChannel.MAGIC, 915)
			.put( OldChannel.SMASH_HITS, 914)
			.put( OldChannel.KERRANG, 913)
			.put( OldChannel.THE_COMMUNITY_CHANNEL, 1288)
			.put( OldChannel.SKY2, 919)
			.put( OldChannel.E_EXLAMATION, 934)
			.put( OldChannel.FLAUNT, 957)
			.put( OldChannel.SCUZZ, 958)
			.put( OldChannel.BLISS, 959)
			.put( OldChannel.ESPN_AMERICA, 962)
			.put( OldChannel.ESPN_AMERICA_HD, 1582)
			.put( OldChannel.DAVE, 74)
			.put( OldChannel.DAVE_JA_VU, 1079)
			.put( OldChannel.PRICE_DROP_TV, 977)
			.put( OldChannel.FX, 984)
			.put( OldChannel.FX_PLUS, 1164)
			.put( OldChannel.EDEN, 993)
			.put( OldChannel.EDEN_PLUS1, 1003)
			.put( OldChannel.EDEN_HD, 1603)
			.put( OldChannel.BLIGHTY, 994)
			.put( OldChannel.THE_HORROR_CHANNEL, 1031)
			.put( OldChannel.THE_HORROR_CHANNEL_PLUS1, 1437)
			.put( OldChannel.RACING_UK, 1051)
			.put( OldChannel.CHELSEA_TV, 1053)
			.put( OldChannel.STAR_NEWS, 1056)
			.put( OldChannel.SETANTA_IRELAND, 1061)
			//dupe .put( OldChannel.LIVINGIT, 1070)
			.put( OldChannel.LIVINGIT_PLUS1, 1470)
			.put( OldChannel.EUROSPORT_2, 1076)
			.put( OldChannel.REALLY, 1084)
			.put( OldChannel.COMEDY_CENTRAL_EXTRA, 974)
			.put( OldChannel.COMEDY_CENTRAL_EXTRA_PLUS1, 1539)
			.put( OldChannel.COMEDY_CENTRAL_HD, 1586)
			.put( OldChannel.M95_TV_MARBELLA, 1130)
			.put( OldChannel.TV3_SPANISH, 1132)
			.put( OldChannel.DISCOVERY_REAL_TIME, 1133)
			.put( OldChannel.DISCOVERY_REAL_TIME_PLUS1, 1135)
			.put( OldChannel.MOTORS_TV, 1141)
			.put( OldChannel.DISCOVERY_SHED, 1150)
			.put( OldChannel.TRUE_MOVIES, 1163)
			.put( OldChannel.SKY3, 1172)
			.put( OldChannel.SKY_3_PLUS1, 1587)
			.put( OldChannel.DISNEY_CINEMAGIC, 1206)
			.put( OldChannel.DISNEY_CINEMAGIC_PLUS1, 1207)
			.put( OldChannel.DISNEY_CINEMAGIC_HD, 1481)
			.put( OldChannel.ESPN_CLASSIC, 1208)
			.put( OldChannel.THREE_E, 1209)
			.put( OldChannel.FILMFLEX, 1224)
			.put( OldChannel.TCM2, 1225)
			// dupe .put( OldChannel.CHRISTMAS24, 1226)
			// dupe .put( OldChannel.CHRISTMAS24_PLUS, 1526)
			.put( OldChannel.DISCOVERY_HD, 1233)
			.put( OldChannel.NATIONAL_GEOGRAPHIC_HD, 1232)
			.put( OldChannel.SKY_BOX_OFFICE_HD1, 1231)
			.put( OldChannel.SKY_BOX_OFFICE_HD2, 1230)
			.put( OldChannel.SKY_SPORTS_1_HD, 1229)
			.put( OldChannel.SKY_SPORTS_2_HD, 1285)
			.put( OldChannel.E_EUROPE, 1305)
			.put( OldChannel.NAT_GEO_WILD, 1307)
			.put( OldChannel.CRIME_AND_INVESTIGATION, 1308)
			.put( OldChannel.CRIME_AND_INVESTIGATION_PLUS1, 1491)
			// dupe .put( OldChannel.SKY_MOVIES_CHRISTMAS_CHANNEL, 1318)
			// dupe .put( OldChannel.SKY_MOVIES_CHRISTMAS_CHANNEL_HD, 1536)
			.put( OldChannel.SKY_MOVIES_CRIME_AND_THRILLER, 1319)
			.put( OldChannel.SKY_MOVIES_CRIME_AND_THRILLER_HD, 1537)
			.put( OldChannel.SKY_MOVIES_PREMIERE, 1320)
			.put( OldChannel.SKY_MOVIES_PREMIERE_PLUS1, 1321)
			.put( OldChannel.SKY_MOVIES_PREMIERE_HD, 1417)
			.put( OldChannel.SKY_MOVIES_COMEDY, 1322)
			.put( OldChannel.SKY_MOVIES_COMEDY_HD, 1449)
			.put( OldChannel.SKY_MOVIES_ACTION_AND_ADVENTURE, 1328)
			.put( OldChannel.SKY_MOVIES_ACTION_AND_ADVENTURE_HD, 1444)
			.put( OldChannel.SKY_MOVIES_FAMILY, 1323)
			.put( OldChannel.SKY_MOVIES_FAMILY_HD, 1448)
			.put( OldChannel.SKY_MOVIES_DRAMA_AND_ROMANCE, 1324)
			.put( OldChannel.SKY_MOVIES_DRAMA_AND_ROMANCE_HD, 1445)
			.put( OldChannel.SKY_MOVIES_SCIFI_HORROR, 1329)
			.put( OldChannel.SKY_MOVIES_SCIFI_HORROR_HD, 1447)
			.put( OldChannel.SKY_MOVIES_CLASSICS, 1325)
			.put( OldChannel.SKY_MOVIES_CLASSICS_HD, 1585)
			.put( OldChannel.SKY_MOVIES_MODERN_GREATS, 1326)
			.put( OldChannel.SKY_MOVIES_MODERN_GREATS_HD, 1446)
			.put( OldChannel.SKY_MOVIES_INDIE, 1327)
			.put( OldChannel.SKY_MOVIES_INDIE_HD, 1514)
			.put( OldChannel.AL_JAZEERA_ENGLISH, 1349)
			.put( OldChannel.HISTORY_HD, 1354)
			.put( OldChannel.SKY1_HD, 1355)
			.put( OldChannel.SKY_ARTS_1_HD, 1356)
			.put( OldChannel.CARTOONITO, 1357)
			.put( OldChannel.BEST_DIRECT, 1361)
			.put( OldChannel.BRAVO_2, 1362)
			.put( OldChannel.DEUTSCHE_WELLE, 1370)
			.put( OldChannel.GEMS_TV, 1365)
			.put( OldChannel.GEM_COLLECTOR, 1366)
			.put( OldChannel.Channel_S, 1371)
			.put( OldChannel.SETANTA_SPORTS_1_IRELAND, 1375)
			.put( OldChannel.DIVA, 1383)
			.put( OldChannel.DIVA_PLUS1, 1525)
			.put( OldChannel.Channel_ONE, 1387)
			.put( OldChannel.Channel_ONE_PLUS1, 1529)
			.put( OldChannel.CN_TOO, 1400)
			.put( OldChannel.POP, 1403)
			.put( OldChannel.TINY_POP, 1402)
			.put( OldChannel.DMAX, 1405)
			.put( OldChannel.DMAX_PLUS1, 1538)
			.put( OldChannel.HORSE_AND_COUNTRY, 1412)
			.put( OldChannel.Channel_7, 1413)
			.put( OldChannel.SKY_SPORTS_3_HD, 1414)
			.put( OldChannel.FLAVA, 1415)
			.put( OldChannel.FX_HD, 1420)
			.put( OldChannel.NATIONAL_GEOGRAPHIC_HD_PAN_EUROPEAN, 1425)
			.put( OldChannel.MOVIES4MEN, 1431)
			.put( OldChannel.MOVIES4MEN_PLUS1, 1541)
			.put( OldChannel.TRUE_MOVIES_2, 1432)
			.put( OldChannel.MOVIES4MEN2, 1433)
			.put( OldChannel.MOVIES4MEN2_PLUS1, 1542)
			.put( OldChannel.MILITARY_HISTORY, 1435)
			.put( OldChannel.THE_STYLE_NETWORK, 1440)
			.put( OldChannel.WATCH, 1441)
			.put( OldChannel.WATCH_PLUS1, 1451)
			.put( OldChannel.SKY_ARTS_2, 1443)
			.put( OldChannel.WEDDING_TV, 1455)
			.put( OldChannel.PROPELLER_TV, 1456)
			.put( OldChannel.MTVN_HD, 1458)
			.put( OldChannel.INVESTIGATION_DISCOVERY, 1460)
			.put( OldChannel.AIT_INTERNATIONAL, 1463)
			.put( OldChannel.CINEMOI, 1473)
			.put( OldChannel.SKY_ARTS_2_HD, 1475)
			.put( OldChannel.BIO_HD, 1479)
			.put( OldChannel.CRIME_AND_INVESTIGATION_HD, 1480)
			.put( OldChannel.NAT_GEO_WILD_HD, 1482)
			.put( OldChannel.QUEST, 1483)
			.put( OldChannel.DISCOVERY_QUEST_PLUS1, 1521)
			.put( OldChannel.QUEST_FREEVIEW, 1604)
			.put( OldChannel.ESPN, 1492)
			.put( OldChannel.ESPN_HD, 1493)
			.put( OldChannel.DISNEY_XD, 1497)
			.put( OldChannel.DISNEY_XD_PLUS1, 1498)
			.put( OldChannel.DISNEY_XD_HD, 1608)
			.put( OldChannel.CBS_REALITY, 1512)
			.put( OldChannel.MGM, 1513)
			.put( OldChannel.CBS_DRAMA, 1518)
			.put( OldChannel.CBS_ACTION, 1520)
			.put( OldChannel.VIVA, 1522)
			.put( OldChannel.FOOD_NETWORK, 1523)
			.put( OldChannel.FOOD_NETWORK_PLUS1, 1524)
			.put( OldChannel.MGM_HD, 1528)
			.put( OldChannel.MTV_SHOWS, 1530)
			.put( OldChannel.NICK_JR_2, 1531)
			.put( OldChannel.NHK_WORLD, 1535)
			.put( OldChannel.TRUEENT, 1548)
			.put( OldChannel.BODY_IN_BALANCE, 1550)
			.put( OldChannel.THE_ACTIVE_CHANNEL, 1551)
			.put( OldChannel.FITNESS_TV, 1552)
			.put( OldChannel.RUSH_HD, 1554)
			.put( OldChannel.BBC_SPORT_INTERACTIVE_BBC_ONE, 1555)
			.put( OldChannel.BBC_SPORT_INTERACTIVE_FREEVIEW, 1558)
			.put( OldChannel.SKY_3D, 1562)
			.put( OldChannel.SKY_SPORTS_4_HD, 1567)
			.put( OldChannel.SKY_ATLANTIC, 1628)
			.put( OldChannel.SKY_ATLANTIC_HD, 1629)
			.put( OldChannel.SKY_MOVIES_SHOWCASE, 1318)
			.put( OldChannel.SKY_MOVIES_SHOWCASE_HD, 1536)
			.put( OldChannel.SKY_LIVING, 122)
			.put( OldChannel.SKY_LIVINGIT, 1070)
			//dupe .put( OldChannel.FX_PLUS, 1164)
			.put( OldChannel.BBC_ALBA, 1442)
			.put( OldChannel.MTV_MUSIC, 1632)
			.put( OldChannel.DISCOVERY_KNOWLEDGE, 128)
			.put( OldChannel.LIVING_PLUS2, 1533)
			.put( OldChannel.S4C2, 658)
			.put( OldChannel.SKY_LIVING_LOVES, 1578)
			.put( OldChannel.ITV1_GRANADA_PLUS1, 1627)
			.put( OldChannel.ITV1_UTV_PLUS1, 1621)
			.put( OldChannel.ITV1_CENTRAL_PLUS1, 1623)
			.put( OldChannel.ITV1_WEST_PLUS1, 1625)
			.put( OldChannel.ITV1_SOUTH_EAST_PLUS1, 1624)
			.put( OldChannel.ITV1_LONDON_PLUS1, 1622)
			.put( OldChannel.ITV1_YORKSHIRE_TYNE_TEES_PLUS1, 1626)
			.put( OldChannel.Q, 965)
			.put( OldChannel.TVE_INTERNACIONAL, 123)
			.put( OldChannel.MOVIES_24, 1226)
			.put( OldChannel.SIMPLY_SHOPPING, 203)
			.put( OldChannel.SUPER_CASINO, 1459)
			.put( OldChannel.MOVIES_24_PLUS, 1526)
			.put( OldChannel.BET_PLUS1, 1540)
			.put( OldChannel.BET_INTERNATIONAL, 58)
			.put( OldChannel.BBC_SPORT_INTERACTIVE_BBC_TWO, 1556)
			.put( OldChannel.BBC_SPORT_INTERACTIVE_BBC_THREE, 1557)
			.put( OldChannel.PBS, 1660)
			.put( OldChannel.BBC_RADIO_RADIO3, 8)
			.put( OldChannel.BBC_RADIO_RADIO4, 33)
			.put( OldChannel.BBC_RADIO_RADIO4_LW, 34)
			.put( OldChannel.BBC_RADIO_RADIO1, 77)
			.put( OldChannel.BBC_RADIO_RADIO2, 86)
			.put( OldChannel.BBC_RADIO_5LIVE, 87)
			.put( OldChannel.CLASSIC_FM_RADIO, 228)
			.put( OldChannel.BBC_RADIO_RADIOSCOTLAND, 232)
			.put( OldChannel.BBC_RADIO_RADIOULSTER, 631)
			.put( OldChannel.BBC_RADIO_RADIOFOYLE, 632)
			.put( OldChannel.BBC_RADIO_RADIOWALES, 633)
			.put( OldChannel.BBC_RADIO_RADIOCYMRU, 634)
			.put( OldChannel.BBC_RADIO_RADIONANGAIDHEAL, 641)
			.put( OldChannel.BBC_RADIO_6MUSIC, 744)
			.put( OldChannel.BBC_RADIO_5LIVESPORTSEXTRA, 745)
			.put( OldChannel.BBC_RADIO_5LIVEOLYMPICSEXTRA, 1685)
			.put( OldChannel.BBC_RADIO_1XTRA, 875)
			.put( OldChannel.BBC_RADIO_RADIO4_EXTRA, 932)
			.put( OldChannel.BBC_RADIO_SURREY, 360)
			.put( OldChannel.BBC_RADIO_SUSSEX, 653)
			.put( OldChannel.XFM_RADIO, 394)
			.put( OldChannel.HEART_LONDON_RADIO, 408)
			.put( OldChannel.BBC_RADIO_ASIANNETWORK, 502)
			.put( OldChannel.TALKSPORT_RADIO, 473)
			.put( OldChannel.CAPITAL_FM, 482)
			.put( OldChannel.BBC_RADIO_MANCHESTER, 493)
			.put( OldChannel.BBC_RADIO_HEREFORDANDWORCESTER, 499)
			.put( OldChannel.BBC_RADIO_BERKSHIRE, 497)
			.put( OldChannel.BBC_RADIO_BRISTOL, 495)
			.put( OldChannel.BBC_RADIO_CAMBRIDGESHIRE, 731)
			.put( OldChannel.BBC_RADIO_TEES, 510)
			.put( OldChannel.BBC_RADIO_CORNWALL, 512)
			.put( OldChannel.BBC_RADIO_CUMBRIA, 514)
			.put( OldChannel.BBC_RADIO_DERBY, 516)
			.put( OldChannel.BBC_RADIO_DEVON, 1309)
			.put( OldChannel.BBC_RADIO_ESSEX, 1345)
			.put( OldChannel.BBC_RADIO_GLOUCESTERSHIRE, 524)
			.put( OldChannel.BBC_RADIO_GUERNSEY, 526)
			.put( OldChannel.BBC_RADIO_HUMBERSIDE, 528)
			.put( OldChannel.BBC_RADIO_JERSEY, 530)
			.put( OldChannel.BBC_RADIO_KENT, 532)
			.put( OldChannel.BBC_RADIO_LANCASHIRE, 534)
			.put( OldChannel.BBC_RADIO_LEEDS, 536)
			.put( OldChannel.BBC_RADIO_LEICESTER, 538)
			.put( OldChannel.BBC_RADIO_LINCOLNSHIRE, 540)
			.put( OldChannel.BBC_RADIO_MERSEYSIDE, 542)
			.put( OldChannel.BBC_RADIO_NEWCASTLE, 544)
			.put( OldChannel.BBC_RADIO_NORFOLK, 546)
			.put( OldChannel.BBC_RADIO_NORTHAMPTON, 548)
			.put( OldChannel.BBC_RADIO_NOTTINGHAM, 550)
			.put( OldChannel.BBC_RADIO_OXFORD, 552)
			.put( OldChannel.BBC_RADIO_SHEFFIELD, 554)
			.put( OldChannel.BBC_RADIO_SHROPSHIRE, 556)
			.put( OldChannel.BBC_RADIO_SOLENT, 1027)
			.put( OldChannel.BBC_RADIO_SOMERSET, 560)
			.put( OldChannel.BBC_RADIO_STOKE, 562)
			.put( OldChannel.BBC_RADIO_SUFFOLK, 564)
			.put( OldChannel.BBC_RADIO_WILTSHIRE, 569)
			.put( OldChannel.BBC_RADIO_YORK, 568)
			.put( OldChannel.ABSOLUTE_RADIO, 575)
			.put( OldChannel.KISS_RADIO, 582)
			.put( OldChannel.BBC_RADIO_WORLDSERVICE, 588)
			.put( OldChannel.MAGIC_RADIO, 590)
			.put( OldChannel.BBC_RADIO_RADIOSCOTLAND_MW, 622)
			.put( OldChannel.BBC_RADIO_RADIOORKNEY, 637)
			.put( OldChannel.BBC_RADIO_RADIOSHETLAND, 638)
			.put( OldChannel.HEAT_RADIO, 973)
			.put( OldChannel.SMASH_HITS_RADIO, 1183)
			.put( OldChannel.KERRANG_RADIO, 1184)
			.put( OldChannel.ABSOLUTE_CLASSIC_ROCK_RADIO, 1331)
			.put( OldChannel.HEART_BERKSHIRE_AND_NORTH_HAMPSHIRE, 233)
			.put( OldChannel.HEART_102_3, 234)
			.put( OldChannel.RADIO_AIRE, 239)
			.put( OldChannel.STAR_RADIO, 240)
			.put( OldChannel.DUBLIN_CITY_FM, 241)
			.put( OldChannel.ARROW_FM, 242)
			.put( OldChannel.BAY, 244)
			.put( OldChannel.RADIO_KERRY, 245)
			.put( OldChannel.BEACH_103_4FM, 246)
			.put( OldChannel.TOUCH_RADIO_102, 248)
			.put( OldChannel.SIGNAL_TWO, 250)
			.put( OldChannel.BORDERS_RADIO, 251)
			.put( OldChannel.HEART_97_1, 253)
			.put( OldChannel.STAR_107_CAMBRIDGE, 255)
			.put( OldChannel.RADIO_CAVELL, 257)
			.put( OldChannel.CENTRAL_FM, 258)
			.put( OldChannel.TOUCH_RADIO_101_6_102_4, 259)
			.put( OldChannel.REAL_RADIO_NORTH_EAST, 260)
			.put( OldChannel.CEREDIGION, 261)
			.put( OldChannel.CFM, 262)
			.put( OldChannel.HEART_ANGLESEY_AND_GWYNEDD, 263)
			.put( OldChannel.CHANNEL_103, 264)
			.put( OldChannel.KFM, 266)
			.put( OldChannel.NINETYEIGHTFM, 273)
			.put( OldChannel.CLARE_FM, 278)
			.put( OldChannel.CLYDE_1, 279)
			.put( OldChannel.CLYDE_2, 280)
			.put( OldChannel.CONNECT_FM, 281)
			.put( OldChannel.CORKS_96FM, 282)
			.put( OldChannel.NINETYEIGHTPOINTTHREE_FM_CORK_CAMPUS_RADIO, 283)
			.put( OldChannel.CUH_FM_107_8, 284)
			.put( OldChannel.COUNTY_SOUND_RADIO, 285)
			.put( OldChannel.C103_WEST_CORK, 286)
			.put( OldChannel.C103_NORTH_AND_EAST_CORK, 287)
			.put( OldChannel.DEVON_MW, 289)
			.put( OldChannel.EAGLE_96_4, 291)
			.put( OldChannel.EAST_COAST_RADIO, 292)
			.put( OldChannel.RED_DOT_RADIO, 293)
			.put( OldChannel.HEART_96_3_102_6, 294)
			.put( OldChannel.FM_104, 295)
			.put( OldChannel.HEART_102_6_97_4, 296)
			.put( OldChannel.FRESH_AM, 297)
			.put( OldChannel.HEART_97_103FM, 299)
			.put( OldChannel.HEART_103, 304)
			.put( OldChannel.HEART_102_7, 305)
			.put( OldChannel.ISLES_FM, 308)
			.put( OldChannel.ISLE_OF_WIGHT_RADIO, 309)
			.put( OldChannel.KLFM, 311)
			.put( OldChannel.NINETYSIXTOONEHUNDREDANDSIX_CAPITAL_FM, 312)
			.put( OldChannel.LM_FM_RADIO, 313)
			.put( OldChannel.LOCHBROOM_FM, 314)
			.put( OldChannel.MAGIC_AM, 315)
			.put( OldChannel.MAGIC_999, 316)
			.put( OldChannel.MERCIA_FM, 318)
			.put( OldChannel.HEART_SUSSEX, 319)
			.put( OldChannel.METRO, 320)
			.put( OldChannel.MINSTER_FM, 321)
			.put( OldChannel.MORAY_FIRTH_RADIO_FM, 322)
			.put( OldChannel.NENE_VALLEY, 323)
			.put( OldChannel.HEART_HOME_COUNTIES, 324)
			.put( OldChannel.NORTHSOUND_ONE, 325)
			.put( OldChannel.NORTHSOUND_TWO, 326)
			.put( OldChannel.HEART_96_7_97_5, 327)
			.put( OldChannel.HEART_96_5_97_1_102_6, 328)
			.put( OldChannel.GLIDE_FM, 329)
			.put( OldChannel.PIRATE_FM, 330)
			.put( OldChannel.NECR_102_1FM, 333)
			.put( OldChannel.HEART_96_6_97FM, 335)
			.put( OldChannel.ONEHUNDREDANDTHREE_POINT_TWO_CAPITAL_FM, 336)
			.put( OldChannel.PREMIER_CHRISTIAN_RADIO, 337)
			.put( OldChannel.RADIO_FIREBIRD, 338)
			.put( OldChannel.Q102_9, 339)
			.put( OldChannel.HEART_103_97_4, 340)
			.put( OldChannel.NINETYSIXPOINTTHREE_ROCK_RADIO, 341)
			.put( OldChannel.NEVIS_RADIO, 342)
			.put( OldChannel.RADIO_MALDWYN, 346)
			.put( OldChannel.RADIO_WAVE, 348)
			.put( OldChannel.RADIO_XL, 349)
			.put( OldChannel.DERBYS_RAM_FM, 350)
			.put( OldChannel.ROCK_FM, 352)
			.put( OldChannel.REVOLUTION, 353)
			.put( OldChannel.REAL_RADIO_SCOTLAND, 356)
			.put( OldChannel.HEART_GLOUCESTERSHIRE, 357)
			.put( OldChannel.SOUTH_EAST_RADIO, 359)
			.put( OldChannel.SOVEREIGN, 364)
			.put( OldChannel.SPECTRUM_558_AM_RADIO, 365)
			.put( OldChannel.SPIRE_FM_RADIO, 366)
			.put( OldChannel.SUNRISE_RADIO, 368)
			.put( OldChannel.SUNRISE_RADIO_103_2FM, 369)
			.put( OldChannel.SUNSHINE_855, 370)
			.put( OldChannel.JUICE_107_2, 371)
			.put( OldChannel.ONEHUNDREDANDSEVENPOINTFOUR_THE_SEVERN, 372)
			.put( OldChannel.TFM_RADIO, 373)
			.put( OldChannel.TIPPERARY_MID_WEST_FM_RADIO, 375)
			.put( OldChannel.TIPP_FM, 376)
			.put( OldChannel.TOWER_107_4FM, 377)
			.put( OldChannel.KISS_105_108, 380)
			.put( OldChannel.VIKING_FM, 381)
			.put( OldChannel.WATERFORD, 383)
			.put( OldChannel.WAVE_105_2FM, 384)
			.put( OldChannel.WAVES_101_2, 385)
			.put( OldChannel.WEST_FM, 386)
			.put( OldChannel.WESSEX_FM, 387)
			.put( OldChannel.WEST_SOUND_FM, 388)
			.put( OldChannel.WESTSOUND_AYRSHIRE_1035AM, 389)
			.put( OldChannel.WISH_FM, 390)
			.put( OldChannel.CHOICE, 391)
			.put( OldChannel.WYVERN_FM, 392)
			.put( OldChannel.YORKSHIRE_COAST_96_2FM, 396)
			.put( OldChannel.TRAX_FM, 399)
			.put( OldChannel.BRMB_96_4, 401)
			.put( OldChannel.CITY_BEAT_96_7_FM, 404)
			.put( OldChannel.KISS_101, 405)
			.put( OldChannel.ONEHUNDREDANDFIVEORSIX_CAPITAL_FM, 406)
			.put( OldChannel.HALLAM_FM, 407)
			.put( OldChannel.HEART_WEST_MIDLANDS, 409)
			.put( OldChannel.TAY_FM, 424)
			.put( OldChannel.TAY_AM, 425)
			.put( OldChannel.SWANSEA, 427)
			.put( OldChannel.TODAY_FM, 428)
			.put( OldChannel.SUN_FM_103_4, 429)
			.put( OldChannel.STRAY, 430)
			.put( OldChannel.WOLF, 439)
			.put( OldChannel.PULSE_2, 440)
			.put( OldChannel.WAVE_96_4FM, 441)
			.put( OldChannel.HEART_97_1_96_4, 442)
			.put( OldChannel.HEART_96_1, 443)
			.put( OldChannel.SIGNAL_ONE_102_6, 444)
			.put( OldChannel.SIGNAL_ONE_FOR_STAFFORD_96_9FM, 445)
			.put( OldChannel.PULSE, 454)
			.put( OldChannel.NINETYSEVENPOINTFOUR_AND_103_2_CAPITAL_FM, 455)
			.put( OldChannel.KEY_103, 456)
			.put( OldChannel.PEAK_107FM, 457)
			.put( OldChannel.MAGIC_1152_MANCHESTER, 460)
			.put( OldChannel.RTE_LYRIC_FM, 461)
			.put( OldChannel.LINCS_FM, 463)
			.put( OldChannel.Q102, 464)
			.put( OldChannel.ISLAND_FM, 465)
			.put( OldChannel.IMAGINE_FM, 466)
			.put( OldChannel.FORTH_ONE, 469)
			.put( OldChannel.FORTH_2, 470)
			.put( OldChannel.DUNE_FM, 471)
			.put( OldChannel.DOWNTOWN_RADIO, 472)
			.put( OldChannel.COOL_FM, 475)
			.put( OldChannel.RADIO_CITY_96_7, 476)
			.put( OldChannel.REAL_RADIO_NORTH_WEST, 477)
			.put( OldChannel.RTE_RAIDIO_NA_GAELTACHTA, 478)
			.put( OldChannel.TWO_FM, 479)
			.put( OldChannel.RTE_RADIO_1_FM, 480)
			.put( OldChannel.HEART_102_4, 481)
			.put( OldChannel.ONEHUNDREDANDFIVE_TO_ONEHUNDREDANDSIX_CAPITAL_FM_SCOTLAND, 489)
			.put( OldChannel.COVENTRY_AND_WARWICKSHIRE_FM, 491)
			.put( OldChannel.BEACON, 503)
			.put( OldChannel.HEART_96_2_97_3, 574)
			.put( OldChannel.ONEHUNDREDANDTWO_CAPITAL_FM, 576)
			.put( OldChannel.ONEHUNDREDANDFIVE_CAPITAL_FM, 577)
			.put( OldChannel.ONEHUNDREDANDTWOPOINTTWO_CAPITAL_FM, 578)
			.put( OldChannel.ONEHUNDREDANDTWOPOINTTWO_SMOOTH_RADIO, 580)
			.put( OldChannel.TOUCH_RADIO_96_2, 583)
			.put( OldChannel.LBC_97_3, 584)
			.put( OldChannel.LIVE_95, 585)
			.put( OldChannel.KINGDOM_FM, 587)
			.put( OldChannel.MAGIC_105_4, 589)
			.put( OldChannel.MAGIC_1170, 591)
			.put( OldChannel.MAGIC_1548, 592)
			.put( OldChannel.MAGIC_828, 593)
			.put( OldChannel.HEART_103_4, 595)
			.put( OldChannel.LBC_NEWS_1152, 596)
			.put( OldChannel.MAGIC_1152_AM, 597)
			.put( OldChannel.WAVE_102FM, 600)
			.put( OldChannel.REAL_RADIO_WALES, 601)
			.put( OldChannel.YORKSHIRE_COAST_BRID_102_4FM, 603)
			.put( OldChannel.ONEHUNDREDANDSEVENPOINTSIX_JUICE_FM, 607)
			.put( OldChannel.MORAY_FIRTH_RADIO_MW, 621)
			.put( OldChannel.HEART_96_4FM, 650)
			.put( OldChannel.HEART_96_3, 651)
			.put( OldChannel.COMPASS_FM, 673)
			.put( OldChannel.FIRE, 716)
			.put( OldChannel.GALWAY_BAY_FM_95_8, 717)
			.put( OldChannel.MANSFIELD_103_2, 718)
			.put( OldChannel.GEM_106, 720)
			.put( OldChannel.RADIO_LINK, 721)
			.put( OldChannel.ONEHUNDREDANDFIVEPOINTSEVEN_SMOOTH_RADIO, 727)
			.put( OldChannel.BRIGHT_106_4, 902)
			.put( OldChannel.RUGBY_FM, 921)
			.put( OldChannel.STAR_107_7, 923)
			.put( OldChannel.HEARTLAND, 926)
			.put( OldChannel.KINGSTOWN, 927)
			.put( OldChannel.STAR_107_2, 930)
			.put( OldChannel.TOTAL_STAR_107_5, 931)
			.put( OldChannel.REAL_RADIO_YORKSHIRE, 940)
			.put( OldChannel.RADIO_PEMBROKESHIRE, 942)
			.put( OldChannel.ONEHUNDREDANDSIXPOINTSIX_SMOOTH_RADIO, 944)
			.put( OldChannel.SPIN_1038, 945)
			.put( OldChannel.SABRAS, 950)
			.put( OldChannel.RADIO_GWENDOLEN, 952)
			.put( OldChannel.SPLASH_FM, 961)
			.put( OldChannel.DREAM_100, 964)
			.put( OldChannel.THE_HITS, 966)
			.put( OldChannel.MAGIC_DIGITAL, 967)
			.put( OldChannel.SPIRIT_FM_96_6_AND_102_3, 968)
			.put( OldChannel.RIVIERA_RADIO, 969)
			.put( OldChannel.BUZZ_ASIA, 970)
			.put( OldChannel.SPECTRUM_FM, 975)
			.put( OldChannel.NORTH_NORFOLK_RADIO, 978)
			.put( OldChannel.BCB_106_6FM, 985)
			.put( OldChannel.ONEHUNDREDPOINTFOUR_SMOOTH_RADIO, 990)
			.put( OldChannel.RTE_RADIO_1_LW, 1008)
			.put( OldChannel.KMFM_106, 1020)
			.put( OldChannel.KMFM_96_2_101_6, 1021)
			.put( OldChannel.KMFM_107_9_100_4, 1022)
			.put( OldChannel.KMFM_107_2, 1023)
			.put( OldChannel.KMFM_96_4_106_8, 1024)
			.put( OldChannel.HEART_KENT, 1025)
			.put( OldChannel.RED_FM, 1029)
			.put( OldChannel.NEWSTALK_106_108_FM, 1034)
			.put( OldChannel.KMFM_105_6, 1052)
			.put( OldChannel.ONEHUNDREDANDFIVEPOINTTWO_SMOOTH_RADIO, 1064)
			.put( OldChannel.BLAST_FM, 1066)
			.put( OldChannel.RADIO_ALTEA, 1080)
			.put( OldChannel.RADIO_SALOBRENA, 1081)
			.put( OldChannel.COASTLINE_RADIO, 1082)
			.put( OldChannel.MIDWEST_RADIO, 1083)
			.put( OldChannel.ONDA_CERO_MARBELLA, 1142)
			.put( OldChannel.THE_BEE, 1170)
			.put( OldChannel.TWOBR, 1171)
			.put( OldChannel.KMFM_107_6, 1173)
			.put( OldChannel.NINETYSIXPOINTFIVE_RADIO_WAVE, 1179)
			.put( OldChannel.U105_8, 1181)
			.put( OldChannel.WYRE_107_2, 1182)
			.put( OldChannel.CONNECT_FM_106_8, 1190)
			.put( OldChannel.HEART_100_5_101_9, 1199)
			.put( OldChannel.ONEHUNDREDANDTHREE_THE_EYE, 1223)
			.put( OldChannel.PLANET_ROCK, 1227)
			.put( OldChannel.XFM_MANCHESTER, 1284)
			.put( OldChannel.RADIO_NORWICH, 1286)
			.put( OldChannel.FOREST_FM, 1287)
			.put( OldChannel.ONEHUNDREDANDTWO_TOWN_FM, 1293)
			.put( OldChannel.THE_SEVERN, 1294)
			.put( OldChannel.RADIO_ORKNEY_MW, 1301)
			.put( OldChannel.RADIO_SHETLAND_MW, 1302)
			.put( OldChannel.ABSOLUTE_XTREME, 1330)
			.put( OldChannel.ARROW, 1333)
			.put( OldChannel.CHILL, 1337)
			.put( OldChannel.FUN_KIDS, 1338)
			.put( OldChannel.UTD_CHRISTIAN_BROADCASTING, 1341)
			.put( OldChannel.WORLD_RADIO_NETWORK, 1342)
			.put( OldChannel.CHOICE_FM, 1344)
			.put( OldChannel.HOPE_FM, 1372)
			.put( OldChannel.GOLD_RADIO, 1377)
			.put( OldChannel.KCFM, 1380)
			.put( OldChannel.IPSWICH_COMMUNITY_RADIO, 1381)
			.put( OldChannel.FUTURE_RADIO, 1382)
			.put( OldChannel.WCR_FM, 1392)
			.put( OldChannel.TEMPO_FM, 1395)
			.put( OldChannel.LEITH, 1396)
			.put( OldChannel.BLACK_DIAMOND, 1397)
			.put( OldChannel.NINETYSEVENPOINTFIVE_SMOOTH_RADIO, 1406)
			.put( OldChannel.CITY_TALK_105_9, 1409)
			.put( OldChannel.CHELMSFORD_RADIO, 1421)
			.put( OldChannel.ONEHUNDREDANDSIXPOINTONE_ROCK_RADIO, 1422)
			.put( OldChannel.LIFE_FM_93_1, 1423)
			.put( OldChannel.NINETYSEVENPOINTFIVE_KEMET_FM, 1436)
			.put( OldChannel.NME_RADIO, 1439)
			.put( OldChannel.JAZZ_FM, 1453)
			.put( OldChannel.COAST_106, 1454)
			.put( OldChannel.RADIO_GRAPEVINE, 1467)
			.put( OldChannel.HEART_WILTSHIRE, 1477)
			.put( OldChannel.NEWPORT_CITY_RADIO, 1487)
			.put( OldChannel.JACK_FM, 1488)
			.put( OldChannel.FOURFM, 1489)
			.put( OldChannel.AMAZING_RADIO, 1490)
			.put( OldChannel.BBC_RADIO_THREECOUNTIES, 1191)
			.put( OldChannel.BBC_RADIO_WM, 570)
			.put( OldChannel.BBC_RADIO_LONDON, 462)
	        .put( OldChannel.FOUR_SEVEN, 1684)
	        .build();
	  
	private static final ImmutableMultimap<OldChannel, Integer> XMLTV_MAP = ImmutableMultimap.<OldChannel, Integer> builder()
			.put( OldChannel.NAT_GEO_WILD, 22)
			.put( OldChannel.ITV1_ANGLIA, 24)
			.put( OldChannel.ITV1_BORDER_SOUTH, 25)
			.put( OldChannel.ITV1_LONDON, 26)
			.put( OldChannel.ITV1_CARLTON_CENTRAL, 27)
			.put( OldChannel.ITV1_CHANNEL, 28)
			.put( OldChannel.ITV1_GRANADA, 29)
			.put( OldChannel.ITV1_MERIDIAN, 30)
			.put( OldChannel.ITV1_TYNE_TEES, 31)
			.put( OldChannel.YTV, 32)
			.put( OldChannel.ITV1_CARLTON_WESTCOUNTRY, 33)
			.put( OldChannel.ITV1_WALES, 35)
			.put( OldChannel.ITV1_WEST, 36)
			.put( OldChannel.STV_CENTRAL, 37)
			.put( OldChannel.ULSTER, 38)
			.put( OldChannel.ANIMAL_PLANET, 39)
			.put( OldChannel.SKY_ARTS_1, 40)
			.put( OldChannel.B4U_MOVIES, 43)
			.put( OldChannel.BBC_THREE, 45)
			.put( OldChannel.BBC_FOUR, 47)
			.put( OldChannel.BBC_NEWS, 48)
			.put( OldChannel.BBC_PARLIMENT, 49)
			.put( OldChannel.BBC_ENTERTAINMENT, 50)
			.put( OldChannel.BBC_ONE, 92)
			.put( OldChannel.BBC_ONE_EAST, 93)
			.put( OldChannel.BBC_ONE, 94)
			.put( OldChannel.BBC_ONE_EAST_MIDLANDS, 95)
			.put( OldChannel.BBC_ONE_NORTH_EAST, 96)
			.put( OldChannel.BBC_ONE_NORTH_EAST, 97)
			.put( OldChannel.BBC_ONE_NORTH_WEST, 98)
			.put( OldChannel.BBC_ONE_NORTHERN_IRELAND, 99)
			.put( OldChannel.BBC_ONE_WALES, 100)
			.put( OldChannel.BBC_ONE_SCOTLAND, 101)
			.put( OldChannel.BBC_ONE_SOUTH, 102)
			.put( OldChannel.BBC_ONE_SOUTH_WEST, 103)
			.put( OldChannel.BBC_ONE_WEST, 104)
			.put( OldChannel.BBC_TWO, 105)
			.put( OldChannel.BBC_TWO, 106)
			.put( OldChannel.BBC_TWO, 107)
			.put( OldChannel.BBC_TWO, 108)
			.put( OldChannel.BBC_TWO, 109)
			.put( OldChannel.BBC_TWO, 110)
			.put( OldChannel.BBC_TWO, 111)
			.put( OldChannel.BBC_TWO_NORTHERN_IRELAND, 112)
			.put( OldChannel.BBC_TWO_SCOTLAND, 113)
			.put( OldChannel.BBC_TWO_WALES, 114)
			.put( OldChannel.BBC_TWO, 115)
			.put( OldChannel.BBC_TWO, 116)
			.put( OldChannel.BBC_TWO, 117)
			.put( OldChannel.BIO, 119)
			.put( OldChannel.BLOOMBERG_TV, 120)
			.put( OldChannel.BRAVO, 122)
			.put( OldChannel.EUROSPORT, 123)
			.put( OldChannel.CNBC, 125)
			.put( OldChannel.CNN, 126)
			.put( OldChannel.CARTOON_NETWORK, 128)
			.put( OldChannel.BOOMERANG_PLUS1, 129)
			.put( OldChannel.CHALLENGE, 131)
			.put( OldChannel.CHANNEL_FOUR, 132)
			.put( OldChannel.FIVE, 134)
			.put( OldChannel.GOD_CHANNEL, 137)
			.put( OldChannel.DISCOVERY, 147)
			.put( OldChannel.DISCOVERY_KNOWLEDGE, 148)
			.put( OldChannel.DISCOVERY_HOME_AND_HEALTH, 149)
			.put( OldChannel.DISCOVERY_REAL_TIME, 150)
			.put( OldChannel.DISCOVERY_PLUS1, 152)
			.put( OldChannel.DISCOVERY_SCIENCE, 153)
			.put( OldChannel.DISCOVERY_TRAVEL_AND_LIVING, 154)
			.put( OldChannel.DISCOVERY_TURBO, 155)
			.put( OldChannel.THE_DISNEY_CHANNEL, 156)
			.put( OldChannel.THE_DISNEY_CHANNEL_PLUS1, 157)
			.put( OldChannel.E_FOUR, 158)
			.put( OldChannel.EURONEWS, 159)
			.put( OldChannel.FILM_4, 160)
			.put( OldChannel.DISNEY_XD, 165)
			.put( OldChannel.DISNEY_XD_PLUS1, 166)
			.put( OldChannel.UNIVERSAL, 180)
			.put( OldChannel.HISTORY, 182)
			.put( OldChannel.HISTORY_PLUS1, 183)
			.put( OldChannel.ITV2, 185)
			.put( OldChannel.KERRANG, 191)
			.put( OldChannel.SKY_LIVING, 197)
			.put( OldChannel.MTV, 202)
			.put( OldChannel.MTV_BASE, 203)
			.put( OldChannel.MTV_HITS, 204)
			.put( OldChannel.MTV_ROCKS, 205)
			.put( OldChannel.MUTV, 206)
			.put( OldChannel.NATIONAL_GEOGRAPHIC, 213)
			.put( OldChannel.NATIONAL_GEOGRAPHIC_PLUS1, 214)
			.put( OldChannel.NICK_JR, 215)
			.put( OldChannel.NICKELODEON_REPLAY, 216)
			.put( OldChannel.NICKELODEON, 217)
			.put( OldChannel.QVC, 228)
			.put( OldChannel.RTE1, 231)
			.put( OldChannel.SKY1, 248)
			.put( OldChannel.SKY_MOVIES_PREMIERE, 249)
			.put( OldChannel.SKY_MOVIES_PREMIERE_PLUS1, 250)
			.put( OldChannel.SKY_MOVIES_INDIE, 253)
			.put( OldChannel.SKY_NEWS, 256)
			.put( OldChannel.SKY_MOVIES_COMEDY, 257)
			.put( OldChannel.SKY_MOVIES_FAMILY, 258)
			.put( OldChannel.SKY_MOVIES_CLASSICS, 259)
			.put( OldChannel.SKY_MOVIES_MODERN_GREATS, 260)
			.put( OldChannel.SKY_SPORTS_1, 262)
			.put( OldChannel.SKY_SPORTS_2, 264)
			.put( OldChannel.SKY_SPORTS_3, 265)
			.put( OldChannel.SONY_ENTERTAINMENT_TV_ASIA, 267)
			.put( OldChannel.TCM, 271)
			.put( OldChannel.TG4, 273)
			.put( OldChannel.TV5, 276)
			.put( OldChannel.THE_BOX, 281)
			.put( OldChannel.LIVING_PLUS2, 287)
			.put( OldChannel.GOLD, 288)
			.put( OldChannel.ALIBI, 292)
			.put( OldChannel.VH1, 293)
			.put( OldChannel.MTV_CLASSIC, 294)
			.put( OldChannel.SKY_SPORTS_NEWS, 300)
			.put( OldChannel.PLAYHOUSE_DISNEY, 421)
			.put( OldChannel.ITV1_BORDER_NORTH, 461)
			.put( OldChannel.CBBC, 482)
			.put( OldChannel.CBEEBIES, 483)
			.put( OldChannel.ZEE_TV, 581)
			.put( OldChannel.EXTREME_SPORTS, 582)
			.put( OldChannel.MAGIC, 588)
			.put( OldChannel.STAR_NEWS, 590)
			.put( OldChannel.STAR_PLUS, 591)
			.put( OldChannel.SMASH_HITS, 592)
			.put( OldChannel.BID_TV, 594)
			.put( OldChannel.KISS, 609)
			.put( OldChannel.MTV_DANCE, 610)
			.put( OldChannel.EDEN_PLUS1, 625)
			.put( OldChannel.ATTHERACES, 661)
			.put( OldChannel.NICKTOONS_TV, 664)
			.put( OldChannel.GOLD_PLUS1, 665)
			.put( OldChannel.S4C, 721)
			.put( OldChannel.CN_TOO, 742)
			.put( OldChannel.YESTERDAY, 801)
			.put( OldChannel.LIVING_PLUS1, 841)
			.put( OldChannel.SKY2, 922)
			.put( OldChannel.TV3_SPANISH, 941)
			.put( OldChannel.COMEDY_CENTRAL, 1061)
			.put( OldChannel.SCUZZ, 1143)
			.put( OldChannel.BLISS, 1144)
			.put( OldChannel.E4_PLUS1, 1161)
			.put( OldChannel.COMEDY_CENTRAL_EXTRA, 1201)
			.put( OldChannel.BRAVO_PLUS1, 1221)
			.put( OldChannel.SKY_BOX_OFFICE_DIGITAL, 1261)
			.put( OldChannel.E_EXLAMATION, 1421)
			.put( OldChannel.FX, 1461)
			.put( OldChannel.TRAVELCHANNEL, 1462)
			.put( OldChannel.YESTERDAY_PLUS1, 1521)
			.put( OldChannel.THE_COMMUNITY_CHANNEL, 1542)
			.put( OldChannel.ESPN_AMERICA, 1543)
			.put( OldChannel.FOUR_MUSIC, 1544)
			.put( OldChannel.EDEN, 1601)
			.put( OldChannel.BLIGHTY, 1602)
			.put( OldChannel.BOOMERANG, 1661)
			.put( OldChannel.CHELSEA_TV, 1741)
			.put( OldChannel.ANIMAL_PLANET_PLUS1, 1761)
			.put( OldChannel.DISCOVERY_REAL_TIME_PLUS1, 1764)
			.put( OldChannel.TELEG, 1804)
			.put( OldChannel.TRAVELCHANNEL_PLUS1, 1855)
			.put( OldChannel.ITV3, 1859)
			.put( OldChannel.BBC_TWO, 1862)
			.put( OldChannel.TVE_INTERNACIONAL, 1865)
			.put( OldChannel.BBC_ONE_SOUTH_EAST, 1869)
			.put( OldChannel.RTE2, 1870)
			.put( OldChannel.CHALLENGE_PLUS1, 1872)
			.put( OldChannel.EUROSPORT_2, 1876)
			.put( OldChannel.REALLY, 1882)
			.put( OldChannel.RACING_UK, 1949)
			.put( OldChannel.DISCOVERY_HOME_AND_HEALTH_PLUS1, 1953)
			.put( OldChannel.MOTORS_TV, 1958)
			.put( OldChannel.MORE_FOUR, 1959)
			.put( OldChannel.ITV4, 1961)
			.put( OldChannel.SKY3, 1963)
			.put( OldChannel.FX_PLUS, 1971)
			.put( OldChannel.MORE4_PLUS1, 1972)
			.put( OldChannel.CITV, 1981)
			.put( OldChannel.CARTOONITO, 1983)
			.put( OldChannel.DISNEY_CINEMAGIC, 1984)
			.put( OldChannel.DISNEY_CINEMAGIC_PLUS1, 1985)
			.put( OldChannel.ITV2_PLUS1, 1990)
			.put( OldChannel.ALIBI_PLUS1, 1993)
			.put( OldChannel.BBC_HD, 1994)
			.put( OldChannel.FIVE_USA, 2008)
			.put( OldChannel.BRAVO_2, 2010)
			.put( OldChannel.ESPN_CLASSIC, 2011)
			.put( OldChannel.COMEDY_CENTRAL_PLUS1, 2013)
			.put( OldChannel.PROPELLER_TV, 2014)
			.put( OldChannel.TCM2, 2016)
			.put( OldChannel.FILM4_PLUS1, 2021)
			.put( OldChannel.BBC_SPORT_INTERACTIVE_FREEVIEW, 2040)
			.put( OldChannel.Channel_4_PLUS1, 2047)
			.put( OldChannel.Channel_ONE, 2049)
			.put( OldChannel.DAVE, 2050)
			.put( OldChannel.DAVE_JA_VU, 2052)
			.put( OldChannel.AL_JAZEERA_ENGLISH, 2055)
			.put( OldChannel.Channel_4_HD, 2056)
			.put( OldChannel.DISCOVERY_SHED, 2057)
			.put( OldChannel.MOVIES4MEN, 2058)
			.put( OldChannel.TRUE_MOVIES, 2059)
			.put( OldChannel.FIVER, 2062)
			.put( OldChannel.BBC_ALBA, 2098)
			.put( OldChannel.WATCH, 2115)
			.put( OldChannel.WATCH_PLUS1, 2116)
			.put( OldChannel.ITV1_HD, 2118)
			.put( OldChannel.SKY_ARTS_2, 2122)
			.put( OldChannel.HOME, 2134)
			.put( OldChannel.HOME_PLUS1, 2135)
			.put( OldChannel.GOOD_FOOD, 2136)
			.put( OldChannel.GOOD_FOOD_PLUS1, 2137)
			.put( OldChannel.SKY1_HD, 2139)
			.put( OldChannel.ESPN, 2142)
			.put( OldChannel.BIO_HD, 2143)
			.put( OldChannel.CRIME_AND_INVESTIGATION_HD, 2144)
			.put( OldChannel.DISCOVERY_HD, 2145)
			.put( OldChannel.DISNEY_CINEMAGIC_HD, 2146)
			.put( OldChannel.ESPN_HD, 2147)
			.put( OldChannel.EUROSPORT_HD, 2148)
			.put( OldChannel.FX_HD, 2149)
			.put( OldChannel.MTVN_HD, 2150)
			.put( OldChannel.NATIONAL_GEOGRAPHIC_HD, 2151)
			.put( OldChannel.NAT_GEO_WILD_HD, 2152)
			.put( OldChannel.SKY_ARTS_1_HD, 2154)
			.put( OldChannel.SKY_ARTS_2_HD, 2155)
			.put( OldChannel.SKY_MOVIES_COMEDY_HD, 2157)
			.put( OldChannel.SKY_MOVIES_FAMILY_HD, 2159)
			.put( OldChannel.SKY_MOVIES_MODERN_GREATS_HD, 2160)
			.put( OldChannel.SKY_MOVIES_SCIFI_HORROR_HD, 2161)
			.put( OldChannel.BBC_WORLD_NEWS, 2164)
			.put( OldChannel.CRIME_AND_INVESTIGATION, 2165)
			.put( OldChannel.SKY_MOVIES_SCIFI_HORROR, 2168)
			.put( OldChannel.Channel_ONE_PLUS1, 2169)
			.put( OldChannel.RUSH_HD, 2173)
			.put( OldChannel.SKY_SPORTS_1_HD, 2174)
			.put( OldChannel.SKY_SPORTS_2_HD, 2175)
			.put( OldChannel.SKY_SPORTS_3_HD, 2176)
			.put( OldChannel.CBS_DRAMA, 2177)
			.put( OldChannel.CBS_ACTION, 2178)
			.put( OldChannel.QUEST, 2179)
			.put( OldChannel.CINEMOI, 2181)
			.put( OldChannel.VIVA, 2184)
			.put( OldChannel.FOOD_NETWORK, 2185)
			.put( OldChannel.FOOD_NETWORK_PLUS1, 2186)
			.put( OldChannel.SKY_LIVINGIT, 2189)
			.put( OldChannel.LIVINGIT_PLUS1, 2190)
			.put( OldChannel.TRUE_MOVIES_2, 2192)
			.put( OldChannel.E4_HD, 2195)
			.put( OldChannel.MGM, 2196)
			.put( OldChannel.CHRISTMAS24, 2197)
			.put( OldChannel.SKY_SPORTS_4, 2200)
			.put( OldChannel.STV_NORTH, 2203)
			.put( OldChannel.SKY_MOVIES_ACTION_AND_ADVENTURE, 2204)
			.put( OldChannel.SKY_MOVIES_ACTION_AND_ADVENTURE_HD, 2205)
			.put( OldChannel.SKY_MOVIES_CRIME_AND_THRILLER, 2206)
			.put( OldChannel.SKY_MOVIES_CRIME_AND_THRILLER_HD, 2207)
			.put( OldChannel.SKY_MOVIES_DRAMA_AND_ROMANCE, 2208)
			.put( OldChannel.SKY_MOVIES_DRAMA_AND_ROMANCE_HD, 2209)
			.put( OldChannel.SKY_MOVIES_CHRISTMAS_CHANNEL, 2210)
			.put( OldChannel.SKY_MOVIES_CHRISTMAS_CHANNEL_HD, 2211)
			.put( OldChannel.SYFY, 2212)
			.put( OldChannel.SYFY_PLUS1, 2213)
			.put( OldChannel.SYFY_HD, 2214)
			.put( OldChannel.SKY_NEWS_HD, 2217)
			.put( OldChannel.STV_HD, 2219)
			.put( OldChannel.BBC_ONE_EAST_MIDLANDS, 2240)
			.put( OldChannel.BBC_TWO, 2241)
			.put( OldChannel.BET_INTERNATIONAL, 2244)
			.put( OldChannel.PHOENIX_CNE, 2246)
			.put( OldChannel.SIMPLY_SHOPPING, 2251)
			.put( OldChannel.GMTV_DIGITAL, 2331)
			.put( OldChannel.S4C2, 2427)
			.put( OldChannel.CHANNEL_9, 2429)
			.put( OldChannel.CHART_SHOW_TV, 2439)
			.put( OldChannel.FLAUNT, 2457)
			.put( OldChannel.THE_HORROR_CHANNEL, 2476)
			.put( OldChannel.SETANTA_IRELAND, 2479)
			.put( OldChannel.M95_TV_MARBELLA, 2487)
			.put( OldChannel.THREE_E, 2502)
			.put( OldChannel.FILMFLEX, 2505)
			.put( OldChannel.ITV3_PLUS1, 2511)
			.put( OldChannel.ITV1_THAMES_VALLEY_NORTH, 2514)
			.put( OldChannel.ITV1_THAMES_VALLEY_SOUTH, 2515)
			.put( OldChannel.E_EUROPE, 2518)
			.put( OldChannel.HISTORY_HD, 2526)
			.put( OldChannel.BEST_DIRECT, 2527)
			.put( OldChannel.GEMS_TV, 2528)
			.put( OldChannel.GEM_COLLECTOR, 2529)
			.put( OldChannel.DEUTSCHE_WELLE, 2530)
			.put( OldChannel.SETANTA_SPORTS_1_IRELAND, 2533)
			.put( OldChannel.DIVA, 2537)
			.put( OldChannel.PLAYHOUSE_DISNEY_PLUS, 2542)
			.put( OldChannel.TINY_POP, 2543)
			.put( OldChannel.POP, 2544)
			.put( OldChannel.DMAX, 2545)
			.put( OldChannel.MTV_PLUS1, 2547)
			.put( OldChannel.HORSE_AND_COUNTRY, 2549)
			.put( OldChannel.Channel_7, 2550)
			.put( OldChannel.FLAVA, 2551)
			.put( OldChannel.SKY_MOVIES_PREMIERE_HD, 2552)
			.put( OldChannel.NATIONAL_GEOGRAPHIC_HD_PAN_EUROPEAN, 2557)
			.put( OldChannel.MOVIES4MEN2, 2558)
			.put( OldChannel.MILITARY_HISTORY, 2559)
			.put( OldChannel.THE_HORROR_CHANNEL_PLUS1, 2561)
			.put( OldChannel.THE_STYLE_NETWORK, 2563)
			.put( OldChannel.WEDDING_TV, 2566)
			.put( OldChannel.ITV4_PLUS1, 2568)
			.put( OldChannel.SUPER_CASINO, 2569)
			.put( OldChannel.INVESTIGATION_DISCOVERY, 2570)
			.put( OldChannel.DISCOVERY_TRAVEL_AND_LIVING_PLUS1, 2574)
			.put( OldChannel.FIVE_USA_PLUS1, 2577)
			.put( OldChannel.FIVER_PLUS1, 2578)
			.put( OldChannel.CRIME_AND_INVESTIGATION_PLUS1, 2583)
			.put( OldChannel.LIVING_HD, 2585)
			.put( OldChannel.CBS_REALITY, 2586)
			.put( OldChannel.SKY_MOVIES_INDIE_HD, 2587)
			.put( OldChannel.DISCOVERY_QUEST_PLUS1, 2588)
			.put( OldChannel.DIVA_PLUS1, 2589)
			.put( OldChannel.CHRISTMAS24_PLUS, 2590)
			.put( OldChannel.UNIVERSAL_PLUS1, 2591)
			.put( OldChannel.MTV_SHOWS, 2592)
			.put( OldChannel.NICK_JR_2, 2593)
			.put( OldChannel.NHK_WORLD, 2594)
			.put( OldChannel.DMAX_PLUS1, 2595)
			.put( OldChannel.COMEDY_CENTRAL_EXTRA_PLUS1, 2596)
			.put( OldChannel.BET_PLUS1, 2597)
			.put( OldChannel.MOVIES4MEN_PLUS1, 2598)
			.put( OldChannel.MOVIES4MEN2_PLUS1, 2599)
			.put( OldChannel.DISCOVERY_SCIENCE_PLUS1, 2600)
			.put( OldChannel.NICKTOONS_REPLAY, 2602)
			.put( OldChannel.TRUEENT, 2603)
			.put( OldChannel.BODY_IN_BALANCE, 2604)
			.put( OldChannel.THE_ACTIVE_CHANNEL, 2605)
			.put( OldChannel.SKY_3D, 2606)
			.put( OldChannel.SKY_SPORTS_4_HD, 2607)
			.put( OldChannel.BBC_SPORT_INTERACTIVE_BBC_TWO, 2610)
			.put( OldChannel.BBC_SPORT_INTERACTIVE_BBC_ONE, 2612)
			.put( OldChannel.BBC_SPORT_INTERACTIVE_BBC_THREE, 2613)
			.put( OldChannel.FIVE_HD, 2615)
			.put( OldChannel.FILM4_HD, 2617)
			.put( OldChannel.DISCOVERY_PLUS1_POINT5, 2619)
			.put( OldChannel.S4C_CLIRLUN, 2624)
			.put( OldChannel.FITNESS_TV, 2638)
			.put( OldChannel.Q, 2639)
			.put( OldChannel.PRICE_DROP_TV, 2640)
			.put( OldChannel.TV3, 2642)
			.put( OldChannel.MGM_HD, 2645)
			.put( OldChannel.COMEDY_CENTRAL_HD, 2646)
			.put( OldChannel.SKY_3_PLUS1, 2647)
			.put( OldChannel.ITV2_HD, 2661)
			.put( OldChannel.EDEN_HD, 2662)
			.put( OldChannel.QUEST_FREEVIEW, 2663)
			.put( OldChannel.BBC_ONE_HD, 2667)
			.put( OldChannel.DISCOVERY_HISTORY, 2668)
			.put( OldChannel.DISCOVERY_HISTORY_PLUS_1, 2672)
			.put( OldChannel.ITV1_GRANADA_PLUS1, 2676)
			.put( OldChannel.ITV1_UTV_PLUS1, 2677)
			.put( OldChannel.ITV1_CENTRAL_PLUS1, 2678)
			.put( OldChannel.ITV1_WEST_PLUS1, 2679)
			.put( OldChannel.ITV1_SOUTH_EAST_PLUS1, 2680)
			.put( OldChannel.ITV1_LONDON_PLUS1, 2682)
			.put( OldChannel.ITV1_YORKSHIRE_TYNE_TEES_PLUS1, 2683)
			.put( OldChannel.SKY_ATLANTIC_HD, 2684)
			.put( OldChannel.SKY_ATLANTIC, 2685)
			.put( OldChannel.SKY_LIVING_LOVES, 2686)
			.put( OldChannel.PBS, 2698)
			.put( OldChannel.FIVE_PLUS1, 2699)
			.build();
	
	private static List<OldChannel> NEW_RADIO_STATIONS = ImmutableList.<OldChannel>builder()
			.add( OldChannel.HEART_BERKSHIRE_AND_NORTH_HAMPSHIRE)
			.add( OldChannel.HEART_102_3)
			.add( OldChannel.RADIO_AIRE)
			.add( OldChannel.STAR_RADIO)
			.add( OldChannel.DUBLIN_CITY_FM)
			.add( OldChannel.ARROW_FM)
			.add( OldChannel.BAY)
			.add( OldChannel.RADIO_KERRY)
			.add( OldChannel.BEACH_103_4FM)
			.add( OldChannel.TOUCH_RADIO_102)
			.add( OldChannel.SIGNAL_TWO)
			.add( OldChannel.BORDERS_RADIO)
			.add( OldChannel.HEART_97_1)
			.add( OldChannel.STAR_107_CAMBRIDGE)
			.add( OldChannel.RADIO_CAVELL)
			.add( OldChannel.CENTRAL_FM)
			.add( OldChannel.TOUCH_RADIO_101_6_102_4)
			.add( OldChannel.REAL_RADIO_NORTH_EAST)
			.add( OldChannel.CEREDIGION)
			.add( OldChannel.CFM)
			.add( OldChannel.HEART_ANGLESEY_AND_GWYNEDD)
			.add( OldChannel.CHANNEL_103)
			.add( OldChannel.KFM)
			.add( OldChannel.NINETYEIGHTFM)
			.add( OldChannel.CLARE_FM)
			.add( OldChannel.CLYDE_1)
			.add( OldChannel.CLYDE_2)
			.add( OldChannel.CONNECT_FM)
			.add( OldChannel.CORKS_96FM)
			.add( OldChannel.NINETYEIGHTPOINTTHREE_FM_CORK_CAMPUS_RADIO)
			.add( OldChannel.CUH_FM_107_8)
			.add( OldChannel.COUNTY_SOUND_RADIO)
			.add( OldChannel.C103_WEST_CORK)
			.add( OldChannel.C103_NORTH_AND_EAST_CORK)
			.add( OldChannel.DEVON_MW)
			.add( OldChannel.EAGLE_96_4)
			.add( OldChannel.EAST_COAST_RADIO)
			.add( OldChannel.RED_DOT_RADIO)
			.add( OldChannel.HEART_96_3_102_6)
			.add( OldChannel.FM_104)
			.add( OldChannel.HEART_102_6_97_4)
			.add( OldChannel.FRESH_AM)
			.add( OldChannel.HEART_97_103FM)
			.add( OldChannel.HEART_103)
			.add( OldChannel.HEART_102_7)
			.add( OldChannel.ISLES_FM)
			.add( OldChannel.ISLE_OF_WIGHT_RADIO)
			.add( OldChannel.KLFM)
			.add( OldChannel.NINETYSIXTOONEHUNDREDANDSIX_CAPITAL_FM)
			.add( OldChannel.LM_FM_RADIO)
			.add( OldChannel.LOCHBROOM_FM)
			.add( OldChannel.MAGIC_AM)
			.add( OldChannel.MAGIC_999)
			.add( OldChannel.MERCIA_FM)
			.add( OldChannel.HEART_SUSSEX)
			.add( OldChannel.METRO)
			.add( OldChannel.MINSTER_FM)
			.add( OldChannel.MORAY_FIRTH_RADIO_FM)
			.add( OldChannel.NENE_VALLEY)
			.add( OldChannel.HEART_HOME_COUNTIES)
			.add( OldChannel.NORTHSOUND_ONE)
			.add( OldChannel.NORTHSOUND_TWO)
			.add( OldChannel.HEART_96_7_97_5)
			.add( OldChannel.HEART_96_5_97_1_102_6)
			.add( OldChannel.GLIDE_FM)
			.add( OldChannel.PIRATE_FM)
			.add( OldChannel.NECR_102_1FM)
			.add( OldChannel.HEART_96_6_97FM)
			.add( OldChannel.ONEHUNDREDANDTHREE_POINT_TWO_CAPITAL_FM)
			.add( OldChannel.PREMIER_CHRISTIAN_RADIO)
			.add( OldChannel.RADIO_FIREBIRD)
			.add( OldChannel.Q102_9)
			.add( OldChannel.HEART_103_97_4)
			.add( OldChannel.NINETYSIXPOINTTHREE_ROCK_RADIO)
			.add( OldChannel.NEVIS_RADIO)
			.add( OldChannel.RADIO_MALDWYN)
			.add( OldChannel.RADIO_WAVE)
			.add( OldChannel.RADIO_XL)
			.add( OldChannel.DERBYS_RAM_FM)
			.add( OldChannel.ROCK_FM)
			.add( OldChannel.REVOLUTION)
			.add( OldChannel.REAL_RADIO_SCOTLAND)
			.add( OldChannel.HEART_GLOUCESTERSHIRE)
			.add( OldChannel.SOUTH_EAST_RADIO)
			.add( OldChannel.SOVEREIGN)
			.add( OldChannel.SPECTRUM_558_AM_RADIO)
			.add( OldChannel.SPIRE_FM_RADIO)
			.add( OldChannel.SUNRISE_RADIO)
			.add( OldChannel.SUNRISE_RADIO_103_2FM)
			.add( OldChannel.SUNSHINE_855)
			.add( OldChannel.JUICE_107_2)
			.add( OldChannel.ONEHUNDREDANDSEVENPOINTFOUR_THE_SEVERN)
			.add( OldChannel.TFM_RADIO)
			.add( OldChannel.TIPPERARY_MID_WEST_FM_RADIO)
			.add( OldChannel.TIPP_FM)
			.add( OldChannel.TOWER_107_4FM)
			.add( OldChannel.KISS_105_108)
			.add( OldChannel.VIKING_FM)
			.add( OldChannel.WATERFORD)
			.add( OldChannel.WAVE_105_2FM)
			.add( OldChannel.WAVES_101_2)
			.add( OldChannel.WEST_FM)
			.add( OldChannel.WESSEX_FM)
			.add( OldChannel.WEST_SOUND_FM)
			.add( OldChannel.WESTSOUND_AYRSHIRE_1035AM)
			.add( OldChannel.WISH_FM)
			.add( OldChannel.CHOICE)
			.add( OldChannel.WYVERN_FM)
			.add( OldChannel.YORKSHIRE_COAST_96_2FM)
			.add( OldChannel.TRAX_FM)
			.add( OldChannel.BRMB_96_4)
			.add( OldChannel.CITY_BEAT_96_7_FM)
			.add( OldChannel.KISS_101)
			.add( OldChannel.ONEHUNDREDANDFIVEORSIX_CAPITAL_FM)
			.add( OldChannel.HALLAM_FM)
			.add( OldChannel.HEART_WEST_MIDLANDS)
			.add( OldChannel.TAY_FM)
			.add( OldChannel.TAY_AM)
			.add( OldChannel.SWANSEA)
			.add( OldChannel.TODAY_FM)
			.add( OldChannel.SUN_FM_103_4)
			.add( OldChannel.STRAY)
			.add( OldChannel.WOLF)
			.add( OldChannel.PULSE_2)
			.add( OldChannel.WAVE_96_4FM)
			.add( OldChannel.HEART_97_1_96_4)
			.add( OldChannel.HEART_96_1)
			.add( OldChannel.SIGNAL_ONE_102_6)
			.add( OldChannel.SIGNAL_ONE_FOR_STAFFORD_96_9FM)
			.add( OldChannel.PULSE)
			.add( OldChannel.NINETYSEVENPOINTFOUR_AND_103_2_CAPITAL_FM)
			.add( OldChannel.KEY_103)
			.add( OldChannel.PEAK_107FM)
			.add( OldChannel.MAGIC_1152_MANCHESTER)
			.add( OldChannel.RTE_LYRIC_FM)
			.add( OldChannel.LINCS_FM)
			.add( OldChannel.Q102)
			.add( OldChannel.ISLAND_FM)
			.add( OldChannel.IMAGINE_FM)
			.add( OldChannel.FORTH_ONE)
			.add( OldChannel.FORTH_2)
			.add( OldChannel.DUNE_FM)
			.add( OldChannel.DOWNTOWN_RADIO)
			.add( OldChannel.COOL_FM)
			.add( OldChannel.RADIO_CITY_96_7)
			.add( OldChannel.REAL_RADIO_NORTH_WEST)
			.add( OldChannel.RTE_RAIDIO_NA_GAELTACHTA)
			.add( OldChannel.TWO_FM)
			.add( OldChannel.RTE_RADIO_1_FM)
			.add( OldChannel.HEART_102_4)
			.add( OldChannel.ONEHUNDREDANDFIVE_TO_ONEHUNDREDANDSIX_CAPITAL_FM_SCOTLAND)
			.add( OldChannel.COVENTRY_AND_WARWICKSHIRE_FM)
			.add( OldChannel.BEACON)
			.add( OldChannel.HEART_96_2_97_3)
			.add( OldChannel.ONEHUNDREDANDTWO_CAPITAL_FM)
			.add( OldChannel.ONEHUNDREDANDFIVE_CAPITAL_FM)
			.add( OldChannel.ONEHUNDREDANDTWOPOINTTWO_CAPITAL_FM)
			.add( OldChannel.ONEHUNDREDANDTWOPOINTTWO_SMOOTH_RADIO)
			.add( OldChannel.TOUCH_RADIO_96_2)
			.add( OldChannel.LBC_97_3)
			.add( OldChannel.LIVE_95)
			.add( OldChannel.KINGDOM_FM)
			.add( OldChannel.MAGIC_105_4)
			.add( OldChannel.MAGIC_1170)
			.add( OldChannel.MAGIC_1548)
			.add( OldChannel.MAGIC_828)
			.add( OldChannel.HEART_103_4)
			.add( OldChannel.LBC_NEWS_1152)
			.add( OldChannel.MAGIC_1152_AM)
			.add( OldChannel.WAVE_102FM)
			.add( OldChannel.REAL_RADIO_WALES)
			.add( OldChannel.YORKSHIRE_COAST_BRID_102_4FM)
			.add( OldChannel.ONEHUNDREDANDSEVENPOINTSIX_JUICE_FM)
			.add( OldChannel.MORAY_FIRTH_RADIO_MW)
			.add( OldChannel.HEART_96_4FM)
			.add( OldChannel.HEART_96_3)
			.add( OldChannel.COMPASS_FM)
			.add( OldChannel.FIRE)
			.add( OldChannel.GALWAY_BAY_FM_95_8)
			.add( OldChannel.MANSFIELD_103_2)
			.add( OldChannel.GEM_106)
			.add( OldChannel.RADIO_LINK)
			.add( OldChannel.ONEHUNDREDANDFIVEPOINTSEVEN_SMOOTH_RADIO)
			.add( OldChannel.BRIGHT_106_4)
			.add( OldChannel.RUGBY_FM)
			.add( OldChannel.STAR_107_7)
			.add( OldChannel.HEARTLAND)
			.add( OldChannel.KINGSTOWN)
			.add( OldChannel.STAR_107_2)
			.add( OldChannel.TOTAL_STAR_107_5)
			.add( OldChannel.REAL_RADIO_YORKSHIRE)
			.add( OldChannel.RADIO_PEMBROKESHIRE)
			.add( OldChannel.ONEHUNDREDANDSIXPOINTSIX_SMOOTH_RADIO)
			.add( OldChannel.SPIN_1038)
			.add( OldChannel.SABRAS)
			.add( OldChannel.RADIO_GWENDOLEN)
			.add( OldChannel.SPLASH_FM)
			.add( OldChannel.DREAM_100)
			.add( OldChannel.THE_HITS)
			.add( OldChannel.MAGIC_DIGITAL)
			.add( OldChannel.SPIRIT_FM_96_6_AND_102_3)
			.add( OldChannel.RIVIERA_RADIO)
			.add( OldChannel.BUZZ_ASIA)
			.add( OldChannel.SPECTRUM_FM)
			.add( OldChannel.NORTH_NORFOLK_RADIO)
			.add( OldChannel.BCB_106_6FM)
			.add( OldChannel.ONEHUNDREDPOINTFOUR_SMOOTH_RADIO)
			.add( OldChannel.RTE_RADIO_1_LW)
			.add( OldChannel.KMFM_106)
			.add( OldChannel.KMFM_96_2_101_6)
			.add( OldChannel.KMFM_107_9_100_4)
			.add( OldChannel.KMFM_107_2)
			.add( OldChannel.KMFM_96_4_106_8)
			.add( OldChannel.HEART_KENT)
			.add( OldChannel.RED_FM)
			.add( OldChannel.NEWSTALK_106_108_FM)
			.add( OldChannel.KMFM_105_6)
			.add( OldChannel.ONEHUNDREDANDFIVEPOINTTWO_SMOOTH_RADIO)
			.add( OldChannel.BLAST_FM)
			.add( OldChannel.RADIO_ALTEA)
			.add( OldChannel.RADIO_SALOBRENA)
			.add( OldChannel.COASTLINE_RADIO)
			.add( OldChannel.MIDWEST_RADIO)
			.add( OldChannel.ONDA_CERO_MARBELLA)
			.add( OldChannel.THE_BEE)
			.add( OldChannel.TWOBR)
			.add( OldChannel.KMFM_107_6)
			.add( OldChannel.NINETYSIXPOINTFIVE_RADIO_WAVE)
			.add( OldChannel.U105_8)
			.add( OldChannel.WYRE_107_2)
			.add( OldChannel.CONNECT_FM_106_8)
			.add( OldChannel.HEART_100_5_101_9)
			.add( OldChannel.ONEHUNDREDANDTHREE_THE_EYE)
			.add( OldChannel.PLANET_ROCK)
			.add( OldChannel.XFM_MANCHESTER)
			.add( OldChannel.RADIO_NORWICH)
			.add( OldChannel.FOREST_FM)
			.add( OldChannel.ONEHUNDREDANDTWO_TOWN_FM)
			.add( OldChannel.THE_SEVERN)
			.add( OldChannel.RADIO_ORKNEY_MW)
			.add( OldChannel.RADIO_SHETLAND_MW)
			.add( OldChannel.ABSOLUTE_XTREME)
			.add( OldChannel.ARROW)
			.add( OldChannel.CHILL)
			.add( OldChannel.FUN_KIDS)
			.add( OldChannel.UTD_CHRISTIAN_BROADCASTING)
			.add( OldChannel.WORLD_RADIO_NETWORK)
			.add( OldChannel.CHOICE_FM)
			.add( OldChannel.HOPE_FM)
			.add( OldChannel.GOLD_RADIO)
			.add( OldChannel.KCFM)
			.add( OldChannel.IPSWICH_COMMUNITY_RADIO)
			.add( OldChannel.FUTURE_RADIO)
			.add( OldChannel.WCR_FM)
			.add( OldChannel.TEMPO_FM)
			.add( OldChannel.LEITH)
			.add( OldChannel.BLACK_DIAMOND)
			.add( OldChannel.NINETYSEVENPOINTFIVE_SMOOTH_RADIO)
			.add( OldChannel.CITY_TALK_105_9)
			.add( OldChannel.CHELMSFORD_RADIO)
			.add( OldChannel.ONEHUNDREDANDSIXPOINTONE_ROCK_RADIO)
			.add( OldChannel.LIFE_FM_93_1)
			.add( OldChannel.NINETYSEVENPOINTFIVE_KEMET_FM)
			.add( OldChannel.NME_RADIO)
			.add( OldChannel.JAZZ_FM)
			.add( OldChannel.COAST_106)
			.add( OldChannel.RADIO_GRAPEVINE)
			.add( OldChannel.HEART_WILTSHIRE)
			.add( OldChannel.NEWPORT_CITY_RADIO)
			.add( OldChannel.JACK_FM)
			.add( OldChannel.FOURFM)
			.add( OldChannel.AMAZING_RADIO)
			.build();
	
	private static final ImmutableMap<OldChannel, String> REDUX_CHANNEL_MAP = ImmutableMap.<OldChannel, String>builder()
			.put(OldChannel.BBC_ONE, "bbcone")
			.put(OldChannel.BBC_TWO, "bbctwo")
			.put(OldChannel.BBC_THREE, "bbcthree")
			.put(OldChannel.BBC_FOUR, "bbcfour")
			.put(OldChannel.CBBC, "cbbc")
			.put(OldChannel.CBEEBIES, "cbeebies")
			.put(OldChannel.BBC_NEWS, "bbcnews24")
			.put(OldChannel.BBC_HD, "bbchd")
			.put(OldChannel.BBC_PARLIMENT, "bbcparl")
			.put(OldChannel.BBC_ONE_HD, "bbconehd")
			.put(OldChannel.ITV1_LONDON, "itv1")
			.put(OldChannel.ITV2, "itv2")
			.put(OldChannel.ITV3, "itv3")
			.put(OldChannel.ITV4, "itv4")
			.put(OldChannel.CHANNEL_FOUR, "channel4")
			.put(OldChannel.E_FOUR, "e4")
			.put(OldChannel.MORE_FOUR, "more4")
			.put(OldChannel.DAVE, "dave")
			.put(OldChannel.FIVE, "five")
			.put(OldChannel.BBC_RADIO_RADIO1, "bbcr1")
			.put(OldChannel.BBC_RADIO_1XTRA, "bbc1x")
			.put(OldChannel.BBC_RADIO_RADIO2, "bbcr2")
			.put(OldChannel.BBC_RADIO_RADIO3, "bbcr3")
			.put(OldChannel.BBC_RADIO_RADIO4, "bbcr4")
			.put(OldChannel.BBC_RADIO_5LIVE, "bbcr5l")
			.put(OldChannel.BBC_RADIO_5LIVESPORTSEXTRA, "r5lsx")
			.put(OldChannel.BBC_RADIO_6MUSIC, "bbc6m")
			.put(OldChannel.BBC_RADIO_RADIO4_EXTRA, "bbc7")
			.put(OldChannel.BBC_RADIO_ASIANNETWORK, "bbcan")
			.put(OldChannel.BBC_RADIO_WORLDSERVICE, "bbcws")
			.build();
		
}
